import {it,expect} from 'vitest';
import {Battle} from '../core/Battle';
import {AMMUNITION,VEHICLE_TYPES} from '../vehicles/Vehicle';
const make=(vehicleLimit=8)=>new Battle({size:8,difficulty:'easy',tickets:500,seed:19,vehicleLimit});
const isolate=(b:Battle)=>{for(const s of b.soldiers)if(!s.player){s.nextAiAt=Infinity;s.nextEquipment=Infinity;s.pos={x:300,z:-300};}for(const v of b.vehicles){v.nextDecision=Infinity;v.pos={x:300,z:300};}};
it('default global cap is balanced across factions and includes air and AA',()=>{const b=make();expect(b.vehicles.filter(v=>v.alive)).toHaveLength(8);for(const team of ['blue','red']){const list=b.vehicles.filter(v=>v.alive&&v.team===team);expect(list).toHaveLength(4);expect(list.some(v=>v.kind==='helicopter')).toBe(true);expect(list.some(v=>v.kind==='aa')).toBe(true);}});
it('a zero vehicle cap disables vehicles and rejects airdrops without charging RP',()=>{const b=make(0);b.awardRP(1000,'test');expect(b.vehicles.filter(v=>v.alive)).toHaveLength(0);expect(b.requestSupport('tank','C').ok).toBe(false);expect(b.requisitionPoints).toBe(1000);});
it('base respawns wait for actual capacity and airdrops count toward the cap',()=>{const b=make();isolate(b);b.awardRP(1000,'test');expect(b.requestSupport('tank','C').ok).toBe(false);const v=b.vehicles[0]!;(b as any).damageVehicle(v,9999,'red');expect(v.respawnAt).toBeGreaterThanOrEqual(90);expect(b.requestSupport('tank','C').ok).toBe(true);const drop=b.vehicles.at(-1)!;expect(drop.airborne).toBe(true);v.respawnAt=0;b.tick(.05);expect(v.alive).toBe(false);expect(b.vehicles.filter(v=>v.alive)).toHaveLength(8);});
it('tank and autocannon spawn distinct ballistic projectiles from their real muzzle',()=>{const shots=[];for(const kind of ['tank','ifv'] as const){const b=make();isolate(b);const v=b.vehicles[0]!;v.kind=kind;v.pos={x:0,z:0};b.player.pos={...v.pos};expect(b.togglePlayerVehicle()).toBe(true);expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(true);shots.push(b.projectiles[0]!);expect(b.projectiles[0]!.gravity).toBe(AMMUNITION[kind].gravity);}expect(shots[0]!.velocity.z).toBeGreaterThan(shots[1]!.velocity.z*2);expect(shots[0]!.gravity).toBeLessThan(shots[1]!.gravity);expect(shots[0]!.radius).toBeLessThan(shots[1]!.radius);expect(VEHICLE_TYPES.tank.respawnDelay).toBe(120);});
it('confirmed damage is actual lost health and a lethal hit is marked once',()=>{const b=make();isolate(b);const enemy=b.soldiers[8]!;enemy.hp=15;enemy.pos={x:0,z:10};(b as any).damage(enemy,100,b.player);(b as any).damage(enemy,100,b.player);const events=b.events().filter(e=>e.type==='hitConfirmed');expect(events).toHaveLength(1);expect(events[0]).toMatchObject({owner:0,target:8,amount:15,killed:true,vehicle:false});});
it('rifle hits can confirm small armor damage but do not instantly destroy tanks',()=>{const b=make();isolate(b);b.player.pos={x:0,z:0};b.playerAiming=true;const v=b.vehicles[1]!;v.pos={x:0,z:15};v.kind='tank';v.hp=820;expect(b.shootPlayer({x:0,y:0,z:1})).toBe(true);expect(v.hp).toBeLessThan(820);expect(v.hp).toBeGreaterThan(810);expect(b.events().some(e=>e.type==='hitConfirmed'&&e.vehicle)).toBe(true);});
it('AI classes have distinct weapons and medics and engineers use real equipment',()=>{const b=make();isolate(b);expect(new Set(b.soldiers.filter(s=>!s.player).map(s=>s.weaponId)).size).toBe(4);const medic=b.soldiers[1]!,engineer=b.soldiers[3]!,v=b.vehicles[0]!;medic.pos={x:0,z:0};medic.hp=30;medic.nextEquipment=0;(b as any).botEquipment(medic);expect(medic.hp).toBe(60);engineer.pos={x:0,z:0};engineer.nextEquipment=0;v.pos={x:0,z:5};v.hp=100;(b as any).botEquipment(engineer);expect(v.hp).toBe(185);});
it('AA accepts a forgiving acquisition cone while rejecting ground and opposite aim targets',()=>{const b=make();isolate(b);b.setLoadout({classId:'engineer'});b.player.pos={x:0,z:0};const v=b.vehicles.find(v=>v.kind==='helicopter'&&v.team==='red')!;v.pos={x:20,z:80};v.altitude=40;expect(b.getAATarget({x:0,y:.45,z:.9})?.id).toBe(v.id);expect(b.getAATarget({x:0,y:0,z:-1})).toBeNull();v.altitude=0;expect(b.getAATarget({x:0,y:0,z:1})).toBeNull();expect(b.aaCount).toBe(2);});

it('AI engineer missiles retain the actual shooter and do not award player credit',()=>{const b=make();isolate(b);const engineer=b.soldiers[11]!,enemy=b.vehicles[0]!;engineer.pos={x:0,z:0};engineer.nextEquipment=0;enemy.pos={x:0,z:30};(b as any).botEquipment(engineer);expect(b.projectiles).toHaveLength(1);expect(b.projectiles[0]!.attackerId).toBe(engineer.id);expect(b.projectiles[0]!.team).toBe('red');for(let i=0;i<30;i++)b.tick(.025);expect(enemy.hp).toBeLessThan(enemy.maxHp);expect(b.requisitionPoints).toBe(0);});
