import {describe,it,expect} from 'vitest';
import {Battle} from '../core/Battle';
import {createVehicle,vehicleMuzzle,VEHICLE_TYPES} from '../vehicles/Vehicle';
const make=()=>new Battle({size:8,difficulty:'normal',tickets:500,seed:911});
function isolate(b:Battle){for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=Infinity;}for(const v of b.vehicles){v.nextDecision=Infinity;v.pos={x:v.team==='red'?320:-320,z:320};}}
describe('Continuous motion and weapon authority',()=>{
 it('advances an AI driven vehicle every simulation tick between decisions',()=>{const b=make();isolate(b);const v=b.vehicles[0]!,driver=b.soldiers[1]!;v.pos={x:0,z:0};v.yaw=0;v.nextDecision=100;v.goal='D';v.route=[{x:0,z:80}];v.nextPath=100;v.movingToGoal=true;driver.vehicleId=v.id;v.occupants[0]=driver.id;v.driver='ai';let changes=0;for(let i=0;i<30;i++){const old={...v.pos};b.tick(1/60);const delta=Math.hypot(v.pos.x-old.x,v.pos.z-old.z);expect(delta).toBeLessThanOrEqual(VEHICLE_TYPES[v.kind].maxForward/60+.001);if(delta>0)changes++;}expect(changes).toBe(30);});
 it('cannot instantly swing a tank barrel to fire behind the hull',()=>{const b=make();isolate(b);const v=b.vehicles[0]!;v.kind='tank';v.pos={x:0,z:0};v.turretYaw=0;b.player.pos={...v.pos};b.togglePlayerVehicle();b.aimPlayerVehicle(0,2,1/60);expect(Math.abs(v.turretYaw)).toBeLessThan(.02);b.shootPlayerVehicle({x:0,y:0,z:-1});const projectile=b.projectiles[0]!;expect(projectile.velocity.z).toBeGreaterThan(0);expect(v.turretPitch).toBeLessThanOrEqual(.55);const muzzle=vehicleMuzzle(v);expect(projectile.pos.x).toBeCloseTo(muzzle.x);expect(projectile.pos.z).toBeCloseTo(muzzle.z);});
 it('clamps scout and aircraft aim arcs, including extreme vertical mouse motion',()=>{const b=make();isolate(b);const v=b.vehicles[0]!;v.kind='scout';v.pos={x:0,z:0};v.yaw=0;b.player.pos={...v.pos};b.togglePlayerVehicle();for(let i=0;i<500;i++)b.aimPlayerVehicle(0,1.4,1/60);expect(Math.abs(v.turretYaw)).toBeLessThanOrEqual(1.9);expect(v.turretPitch).toBeLessThanOrEqual(.55);});
 it('unstuck relocates without healing, adding ammunition or costing a ticket, and has a cooldown',()=>{const b=make();isolate(b);b.player.hp=43;const tickets=b.tickets.blue,ammo=b.playerAmmo;expect(b.unstuckPlayer()).toBe(true);expect(b.player.hp).toBe(43);expect(b.playerAmmo).toBe(ammo);expect(b.tickets.blue).toBe(tickets);expect(b.unstuckPlayer()).toBe(false);});
});
describe('Aircraft and anti-air are real battle objects',()=>{
 it('has seven distinct vehicle configurations and pilot seat counts',()=>{const b=make();expect(new Set(b.vehicles.map(v=>v.kind)).size).toBe(7);expect(createVehicle(99,'blue','jet',{x:0,z:0}).seatCount).toBe(1);expect(createVehicle(98,'blue','helicopter',{x:0,z:0}).seatCount).toBe(4);});
 it('flies with a real driver and falls under gravity after the driver leaves',()=>{const b=make();isolate(b);const v=b.vehicles.find(v=>v.kind==='helicopter'&&v.team==='blue')!;v.pos={x:0,z:0};b.player.pos={...v.pos};b.togglePlayerVehicle();for(let i=0;i<180;i++){b.changeAltitude(1,1/60);b.drivePlayerVehicle(1,0,1/60,-Math.PI);b.tick(1/60);}expect(v.altitude).toBeGreaterThan(17);expect(v.pos.z).toBeGreaterThan(5);expect(b.togglePlayerVehicle()).toBe(true);const height=v.altitude;for(let i=0;i<240;i++)b.tick(1/60);expect(v.altitude).toBeLessThan(height);});
 it('AA only locks airborne enemies in the aim cone and consumes finite missiles',()=>{const b=make();isolate(b);b.setLoadout({classId:'engineer'});b.player.pos={x:0,z:0};const v=b.vehicles.find(v=>v.kind==='helicopter'&&v.team==='red')!;v.pos={x:0,z:60};v.altitude=30;expect(b.fireAA({x:0,y:0,z:-1})).toBe(false);expect(b.aaCount).toBe(2);const d={x:0,y:.447,z:.894};expect(b.getAATarget(d)?.id).toBe(v.id);expect(b.fireAA(d)).toBe(true);expect(b.projectiles[0]?.targetId).toBe(v.id);expect(b.aaCount).toBe(1);const hp=v.hp;for(let i=0;i<100;i++)b.tick(.025);expect(v.hp).toBeLessThan(hp);expect(b.fireAA(d)).toBe(false);});
 it('airdrops each new vehicle and reserves it for the summoning soldier',()=>{for(const kind of ['aa','helicopter','jet'] as const){const b=make();isolate(b);b.awardRP(1000,'qa');expect(b.requestSupport(kind,'C').ok).toBe(true);const v=b.vehicles.at(-1)!;expect(v.kind).toBe(kind);expect(v.airborne).toBe(true);expect(v.reservedFor).toBe(b.player.id);expect(v.driver).toBe(null);}});
 it('emits directional vehicle damage and grants repair score only for actual repairs',()=>{const b=make();isolate(b);b.setLoadout({classId:'engineer'});const v=b.vehicles[0]!;v.pos={x:0,z:0};b.player.pos={x:0,z:8};(b as any).damageVehicle(v,40,'red',false,{x:30,z:0});expect(b.events()).toContainEqual({type:'vehicleHit',id:v.id,amount:40,from:{x:30,z:0}});expect(b.useGadget()).toBe(true);expect(v.hp).toBe(v.maxHp);expect(b.requisitionPoints).toBe(6);});
 it('serializes human control contexts without sharing seats, ammo or RP',()=>{const b=make(),first=b.exportPlayerState();b.controlledPlayerId=1;b.importPlayerState(first);b.awardRP(60,'kill');b.switchPlayerWeapon('marksman');const second=b.exportPlayerState();b.controlledPlayerId=0;b.importPlayerState(first);expect(b.requisitionPoints).toBe(0);expect(b.playerWeapon).toBe('carbine');b.controlledPlayerId=1;b.importPlayerState(second);expect(b.requisitionPoints).toBe(60);expect(b.playerWeapon).toBe('marksman');});
});

describe('Faction and squad deployment',()=>{
 it('uses the red base, red squad and red flags for a red human',()=>{const b=make();isolate(b);b.controlledPlayerId=8;b.player.player=true;b.soldiers[0]!.player=false;b.player.alive=false;b.player.respawnAt=0;b.points[1]!.owner='red';const locations=b.getDeploymentLocations();expect(locations.find(l=>l.id==='BASE')?.at.x).toBeGreaterThan(200);expect(locations.find(l=>l.id==='B')?.available).toBe(true);expect(locations.some(l=>l.id==='SQUAD-9')).toBe(true);expect(locations.some(l=>l.id==='SQUAD-1')).toBe(false);expect(b.respawnPlayer('BASE')).toBe(true);expect(b.player.pos.x).toBeGreaterThan(200);expect(b.getSquadMembers()).toHaveLength(4);});
 it('red fire, artillery and summoned vehicles keep the shooter faction',()=>{const b=make();isolate(b);b.controlledPlayerId=8;b.player.player=true;b.player.pos={x:0,z:0};expect(b.shootPlayer({x:0,y:0,z:1})).toBe(true);expect(b.events().some(e=>e.type==='shot'&&e.team==='red')).toBe(true);b.awardRP(1000,'qa');b.requestSupport('tank','C');expect(b.vehicles.at(-1)?.team).toBe('red');b.requestSupport('artillery','C');expect(b.supports.at(-1)?.team).toBe('red');});
 it('deploys directly into an empty safe vehicle seat and refuses full, destroyed or fighting vehicles',()=>{const b=make();isolate(b);const v=b.vehicles[0]!;v.pos={x:0,z:0};b.player.alive=false;b.player.respawnAt=0;expect(b.respawnPlayer('VEHICLE-0-1')).toBe(true);expect(b.playerSeat).toBe(1);expect(b.player.vehicleId).toBe(v.id);expect(v.occupants[1]).toBe(b.player.id);b.togglePlayerVehicle();b.player.alive=false;v.combatUntil=8;expect(b.respawnPlayer('VEHICLE-0-0')).toBe(false);v.combatUntil=0;v.alive=false;expect(b.respawnPlayer('VEHICLE-0-0')).toBe(false);v.alive=true;v.occupants.fill(3);expect(b.getDeploymentLocations().find(l=>l.id==='VEHICLE-0')?.reason).toBe('座位已满');});
 it('disabling AI stops automatic AI respawns',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500,aiEnabled:false});for(const s of b.soldiers)if(!s.player){s.alive=false;s.respawnAt=0;}for(let i=0;i<60;i++)b.tick(.05);expect(b.soldiers.filter(s=>s.alive)).toHaveLength(1);});
});
