import {describe,it,expect} from 'vitest';
import {Battle} from '../core/Battle';
import {Commander} from '../ai/Commander';
import {controlFlight,guideMissile} from '../vehicles/Flight';
import {createVehicle,VEHICLE_TYPES} from '../vehicles/Vehicle';
import {Navigation} from '../ai/Navigation';
import {collides} from '../world/Layout';
function isolate(b:Battle){for(const s of b.soldiers){s.alive=false;s.respawnAt=Infinity;}for(const v of b.vehicles){v.alive=false;v.respawnAt=Infinity;}b.player.alive=true;b.player.pos={x:-340,z:340};}
describe('commander observes, assigns and respects human control',()=>{
 it('does not report a hidden enemy as a visual contact',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:1000,seed:91});isolate(b);const a=b.soldiers[1]!,e=b.soldiers[8]!;a.alive=e.alive=true;a.pos={x:-193,z:-216};e.pos={x:-193,z:-208};a.yaw=0;e.nextAiAt=Infinity;expect(b.sightBlocked(a.pos,e.pos)).toBe(true);b.tick(.05);expect(b.intelligence.blue.snapshot(b.elapsed).filter(r=>r.kind==='ENEMY_OBSERVED')).toEqual([]);});
 it('actual visible observation freezes once sight is lost',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:1000,seed:19});isolate(b);const a=b.soldiers[1]!,e=b.soldiers[8]!;a.alive=e.alive=true;a.pos={x:0,z:0};a.yaw=0;a.nextAiAt=0;e.pos={x:0,z:20};e.nextAiAt=Infinity;b.tick(.05);const contact=b.intelligence.blue.snapshot(b.elapsed).find(r=>r.subject==='soldier:8')!;expect(contact).toBeDefined();a.nextAiAt=Infinity;e.pos={x:320,z:320};for(let i=0;i<100;i++)b.tick(.05);const lost=b.intelligence.blue.snapshot(b.elapsed).find(r=>r.subject==='soldier:8')!;expect(lost.at).toEqual(contact.at);expect(lost.confidenceNow).toBeLessThan(contact.confidenceNow);});
 it('distributes missions, retains them, and adapts to a failed route',()=>{const c=new Commander('blue'),map=[{id:'A',x:0,z:0},{id:'B',x:50,z:0},{id:'C',x:100,z:0}],squads=Array.from({length:4},(_,squad)=>({squad,leader:squad*4,at:{x:50,z:-20},members:4,health:1,blocked:false,human:squad===0}));c.evaluate(0,map,[],squads,500,500);expect(new Set([...c.assignments.values()].map(a=>a.objective)).size).toBe(3);const old=c.assignments.get(0)!;c.evaluate(4,map,[],squads,500,500);expect(c.assignments.get(0)!.objective).toBe(old.objective);c.evaluate(5,map,[],squads.map(s=>({...s,blocked:s.squad===0})),500,500);expect(c.assignments.get(0)!.objective).not.toBe(old.objective);expect(c.assignments.get(0)!.reason).toContain('情报');});
 it('dismissal suppresses repeated advice and accepting changes AI goals, never human position',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500});const before={...b.player.pos};expect(b.respondRecommendation(false)).toBe(true);(b as any).assignSquads();expect(b.getRecommendation()?.status).toBe('dismissed');expect(b.player.pos).toEqual(before);b.elapsed=46;(b as any).assignSquads();const r=b.getRecommendation()!;expect(b.respondRecommendation(true)).toBe(true);expect(b.soldiers.filter(s=>s.squad===b.player.squad&&s.team===b.player.team&&!s.player).every(s=>s.goal===r.objective)).toBe(true);expect(b.player.pos).toEqual(before);});
});
describe('distinct mobility, countermeasures and real navigation',()=>{
 it('jet banks, turns, cannot reverse; helicopter translates sideways and can hover',()=>{const jet=createVehicle(99,'blue','jet',{x:0,z:0}),heli=createVehicle(98,'blue','helicopter',{x:0,z:0});for(let i=0;i<120;i++)controlFlight(jet,1,1,1/60,undefined,.4,true);expect(jet.roll).toBeGreaterThan(.8);expect(jet.yaw).toBeGreaterThan(1);expect(jet.speed).toBeGreaterThan(30);expect(jet.flightPitch).toBeGreaterThan(.3);const move=controlFlight(heli,0,1,.1, -Math.PI);expect(move.x).toBeGreaterThan(1);expect(heli.speed).toBe(0);expect(jet.speed).not.toBe(heli.speed);});
 it('separates lock warning from incoming; flares cancel both stages and prevent reacquisition during protection',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500});isolate(b);const v=b.vehicles.find(v=>v.kind==='aa'&&v.team==='blue')!,t=b.vehicles.find(v=>v.kind==='helicopter'&&v.team==='red')!;v.alive=t.alive=true;v.pos={x:0,z:0};t.pos={x:0,z:80};t.altitude=30;v.occupants[0]=b.player.id;b.player.vehicleId=v.id;v.weaponSlot=1;v.turretYaw=0;v.turretPitch=.35;for(let i=0;i<35;i++){b.elapsed+=.05;(b as any).updateVehicleLock(v,.05);}expect(v.lockProgress).toBe(1);expect(t.warningUntil).toBeGreaterThan(b.elapsed);expect(t.incomingUntil).toBe(0);expect((b as any).fireVehicleMissile(v,true)).toBe(true);expect(t.incomingUntil).toBeGreaterThan(b.elapsed);expect(b.deployFlares(t)).toBe(true);expect(b.projectiles[0]?.targetId).toBeUndefined();expect(v.lockProgress).toBe(0);(b as any).updateVehicleLock(v,.1);expect(v.lockTarget).toBeNull();expect(t.warningUntil).toBe(0);expect(t.incomingUntil).toBe(0);expect(b.deployFlares(t)).toBe(false);});
 it('missile has bounded turn rate and a fast crossing can break the seeker without flares',()=>{const v={x:0,y:0,z:145};expect(guideMissile(v,{x:20,y:0,z:100},145,.05)).toBe(true);expect(Math.atan2(v.x,v.z)).toBeLessThanOrEqual(.0626);expect(Math.hypot(v.x,v.y,v.z)).toBeCloseTo(145);expect(guideMissile(v,{x:100,y:0,z:-10},145,.05)).toBe(false);});
 it('motorcycle has two seats and distinct acceleration, no driver or passenger gun',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500});isolate(b);const v=b.vehicles.find(v=>v.kind==='motorcycle'&&v.team==='blue')!;v.alive=true;v.pos={x:0,z:0};b.player.pos={...v.pos};expect(v.seatCount).toBe(2);expect(b.togglePlayerVehicle()).toBe(true);b.drivePlayerVehicle(1,0,.3);expect(v.speed).toBeGreaterThan(5);expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(false);expect(VEHICLE_TYPES.motorcycle.radius).toBeLessThan(VEHICLE_TYPES.transport.radius);});
 it('vehicle routes validate swept hull clearance instead of cutting through obstacles',()=>{const nav=new Navigation(3.8,true),from={x:-315,z:-170},to={x:-220,z:-170},route=nav.find(from,to);expect(route.length).toBeGreaterThan(1);let prev=from;for(const p of route){for(let t=0;t<=1;t+=.03)expect(collides(prev.x+(p.x-prev.x)*t,prev.z+(p.z-prev.z)*t,3.8)).toBe(false);prev=p;}});
});
describe('squad transport and navigation recovery',()=>{
 it('AI transports disembark real occupants on arrival and retain mission goals',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500});isolate(b);const v=b.vehicles.find(v=>v.kind==='transport'&&v.team==='blue')!,p=b.points[2]!;v.alive=true;v.pos={x:p.x,z:p.z};v.goal=p.id;v.nextDecision=Infinity;v.movingToGoal=false;for(let seat=0;seat<3;seat++){const s=b.soldiers[seat+4]!;s.alive=true;s.pos={...v.pos};s.vehicleId=v.id;v.occupants[seat]=s.id;}b.tick(.05);expect(v.occupants.every(id=>id===null)).toBe(true);expect(v.driver).toBeNull();for(const s of b.soldiers.slice(4,7)){expect(s.vehicleId).toBeNull();expect(s.goal).toBe(p.id);expect(s.boardingUntil).toBeGreaterThan(b.elapsed+20);}});
 it('blocked hull path reports failure without teleporting',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500});isolate(b);const v=b.vehicles[0]!;v.alive=true;v.pos={x:-269,z:-170};v.lastProgress={...v.pos};const original={...v.pos};for(let n=0;n<160;n++){b.elapsed+=.05;(b as any).vehicleMove(v,{x:0,z:0},.05);}expect(v.pos).toEqual(original);expect(b.intelligence.blue.snapshot(b.elapsed).some(r=>r.kind==='NAVIGATION_BLOCKED')).toBe(true);});
 it('handheld anti-air acquisition and launch also produce two warning stages',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500});isolate(b);b.setLoadout({classId:'engineer'});b.player.pos={x:0,z:0};const v=b.vehicles.find(v=>v.team==='red'&&v.kind==='helicopter')!;v.alive=true;v.pos={x:0,z:60};v.altitude=30;const dir={x:0,y:.447,z:.894};b.warnAATarget(dir);expect(v.warningUntil).toBeGreaterThan(b.elapsed);expect(v.incomingUntil).toBe(0);expect(b.fireAA(dir)).toBe(true);expect(v.incomingUntil).toBeGreaterThan(b.elapsed);});
});
it('a jet can physically evade an incoming missile through a fast crossing maneuver',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:500});isolate(b);const source=b.vehicles.find(v=>v.kind==='aa'&&v.team==='blue')!,jet=b.vehicles.find(v=>v.kind==='jet'&&v.team==='red')!,pilot=b.soldiers[8]!;source.alive=jet.alive=true;source.pos={x:0,z:0};jet.pos={x:0,z:110};jet.altitude=45;jet.yaw=Math.PI/2;jet.speed=90;pilot.alive=true;pilot.player=true;pilot.vehicleId=jet.id;jet.occupants[0]=pilot.id;jet.driver='player';source.lockTarget=jet.id;source.lockProgress=1;expect((b as any).fireVehicleMissile(source,true)).toBe(true);const hp=jet.hp;let lost=false;for(let n=0;n<120;n++){(b as any).flyVehicle(jet,1,.4,.05,undefined,0,true);b.tick(.05);if(b.projectiles.some(p=>p.kind==='rocket'&&p.targetId===undefined))lost=true;}expect(lost).toBe(true);expect(jet.hp).toBe(hp);expect(jet.flareUntil).toBe(0);});
