import {describe,it,expect} from 'vitest';
import {createCapturePoints,updateCapture,bleedRate} from '../gameplay/Conquest';
import {Battle} from '../core/Battle';
import {collides,lineBlocked,COVER_POINTS} from '../world/Layout';
import {WEAPONS} from '../combat/Weapons';

describe('Conquest logic',()=>{
 it('captures, neutralizes and recaptures',()=>{const p=createCapturePoints()[0]!,unit={alive:true,team:'blue' as const,pos:{x:0,z:0}};unit.pos={x:p.x,z:p.z};for(let i=0;i<12;i++)updateCapture(p,[unit],1);expect(p.owner).toBe('blue');expect(p.control).toBe(100);const red={...unit,team:'red' as const};for(let i=0;i<8;i++)updateCapture(p,[red],1);expect(p.owner).toBe(null);for(let i=0;i<8;i++)updateCapture(p,[red],1);expect(p.owner).toBe('red')});
 it('freezes a contested objective',()=>{const p=createCapturePoints()[0]!,a={alive:true,team:'blue' as const,pos:p},b={...a,team:'red' as const};updateCapture(p,[a,b],20);expect(p.contested).toBe(true);expect(p.control).toBe(0)});
 it('bleeds tickets only against the team with fewer flags',()=>{const p=createCapturePoints();p[0]!.owner='red';p[1]!.owner='red';p[2]!.owner='blue';expect(bleedRate(p,'blue')).toBeGreaterThan(0);expect(bleedRate(p,'red')).toBe(0)});
});

describe('World and loadout rules',()=>{
 it('blocks solid structures and exposes generated cover',()=>{expect(collides(-269,-170,1)).toBe(true);expect(lineBlocked({x:-315,z:-170},{x:-220,z:-170})).toBe(true);expect(COVER_POINTS.length).toBeGreaterThan(25)});
 it('switches weapons with independent magazines',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:100,seed:2});expect(b.playerAmmo).toBe(WEAPONS.carbine.magazine);expect(b.switchPlayerWeapon('marksman')).toBe(true);expect(b.playerAmmo).toBe(WEAPONS.marksman.magazine);expect(b.activeWeapon.id).toBe('marksman')});
 it('lets the player enter, drive, fire and exit the armored vehicle',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:100,seed:44}),blue=b.vehicles.find(v=>v.team==='blue')!,red=b.vehicles.find(v=>v.team==='red')!;blue.pos={x:0,z:0};blue.lastProgress={...blue.pos};blue.nextDecision=9999;red.pos={x:0,z:24};red.lastProgress={...red.pos};red.nextDecision=9999;b.player.pos={...blue.pos};expect(b.togglePlayerVehicle()).toBe(true);b.drivePlayerVehicle(1,0,.5);expect(Math.hypot(blue.pos.x,blue.pos.z)).toBeGreaterThan(.1);blue.pos={x:0,z:0};b.player.pos={...blue.pos};for(let i=0;i<9;i++){expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(true);for(let k=0;k<10;k++)b.tick(.125);red.pos={x:0,z:24};red.nextDecision=9999}expect(red.alive).toBe(false);expect(b.togglePlayerVehicle()).toBe(true);expect(b.inVehicle).toBe(false)});
});

describe('Autonomous battle AI',()=>{
 it('uses survival behavior when a weak bot is threatened',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:100,seed:19}),blue=b.soldiers.find(s=>s.team==='blue'&&!s.player)!,red=b.soldiers.find(s=>s.team==='red')!;blue.pos={x:5,z:0};blue.lastProgress={...blue.pos};blue.hp=52;blue.suppression=.92;blue.spawnGraceUntil=0;blue.nextAiAt=0;red.pos={x:5,z:10};red.lastProgress={...red.pos};red.spawnGraceUntil=0;red.nextAiAt=0;const seen=new Set<string>();for(let i=0;i<30;i++){b.tick(.05);seen.add(blue.state)}expect([...seen].some(x=>['RETREAT','SEEK_COVER','ENGAGE'].includes(x))).toBe(true)});
 it('uses approximate hearing to search for a nearby enemy behind cover',()=>{const b=new Battle({size:8,difficulty:'normal',tickets:100,seed:91}),blue=b.soldiers.find(s=>s.team==='blue'&&!s.player)!,red=b.soldiers.find(s=>s.team==='red')!;blue.pos={x:-193,z:-216};blue.lastProgress={...blue.pos};blue.spawnGraceUntil=0;blue.nextAiAt=0;red.pos={x:-193,z:-208};red.lastProgress={...red.pos};red.spawnGraceUntil=0;red.nextAiAt=999;expect(lineBlocked(blue.pos,red.pos)).toBe(true);const states=new Set<string>();for(let i=0;i<24;i++){b.tick(.05);states.add(blue.state)}expect(states.has('SEARCH')).toBe(true)});
 it('moves, fights, captures, respawns and finishes without a player',()=>{const battle=new Battle({size:16,difficulty:'normal',tickets:36,seed:102}),start=battle.soldiers.map(s=>({...s.pos})),states=new Set<string>();let captureSeen=false,deathSeen=false,respawnSeen=false;for(let i=0;i<40000&&!battle.finished;i++){battle.tick(.125);for(const s of battle.soldiers)if(!s.player)states.add(s.state);for(const e of battle.events()){if(e.type==='capture')captureSeen=true;if(e.type==='death')deathSeen=true;if(e.type==='respawn')respawnSeen=true}}expect(battle.soldiers.some((s,i)=>!s.player&&Math.hypot(s.pos.x-start[i]!.x,s.pos.z-start[i]!.z)>35)).toBe(true);expect(captureSeen).toBe(true);expect(deathSeen).toBe(true);expect(respawnSeen).toBe(true);expect(states.has('ENGAGE')).toBe(true);expect(states.has('FOLLOW_SQUAD')).toBe(true);expect(battle.finished).toBe(true);expect(battle.winner).not.toBeNull()});
 it('finishes the primary 32v32 battle with the default 500 tickets while the player is idle',()=>{const battle=new Battle({size:32,difficulty:'normal',tickets:500,killTicketPenalty:1,seed:505});let captures=0,deaths=0,shots=0,impacts=0;const events=new Set<string>();for(let i=0;i<24000&&!battle.finished;i++){battle.tick(.125);for(const e of battle.events()){if(e.type==='capture')captures++;if(e.type==='death')deaths++;if(e.type==='shot')shots++;if(e.type==='artilleryImpact')impacts++;if(e.type==='majorEvent'&&e.action==='start')events.add(e.kind)}}expect(battle.finished).toBe(true);expect(battle.winner).not.toBeNull();expect(captures).toBeGreaterThan(0);expect(deaths).toBeGreaterThan(0);expect(shots).toBeGreaterThan(0);expect(impacts).toBeGreaterThanOrEqual(4);expect([...events].sort()).toEqual(['ARMORED_PUSH','ARTILLERY','COUNTER_OFFENSIVE']);expect(battle.getNavigationFailures()).toBeLessThan(10)});
});
