import {describe,it,expect} from 'vitest';
import {Battle} from '../core/Battle';
import {validateLoadout,CLASSES} from '../combat/Weapons';
const make=()=>new Battle({size:8,vehicleLimit:20,difficulty:'normal',tickets:500,seed:911});
const run=(b:Battle,t:number)=>{for(let i=0;i<t/.025;i++)b.tick(.025)};
function isolate(b:Battle){for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;s.spawnGraceUntil=0;}for(const v of b.vehicles){v.nextDecision=1e9;v.pos={x:v.team==='red'?320:-320,z:320};}}
function die(b:Battle){b.player.alive=false;b.player.respawnAt=0;}
describe('Safe deployment authority',()=>{
 it('spawns beside a safe squadmate and refuses an engaged or dead one',()=>{const b=make();isolate(b);const mate=b.soldiers[1]!;mate.pos={x:0,z:0};mate.state='DEFEND';die(b);expect(b.respawnPlayer('SQUAD-1')).toBe(true);expect(Math.hypot(b.player.pos.x,b.player.pos.z)).toBeGreaterThan(1.5);expect(Math.hypot(b.player.pos.x,b.player.pos.z)).toBeLessThan(6);die(b);mate.combatUntil=8;expect(b.respawnPlayer('SQUAD-1')).toBe(false);mate.combatUntil=0;mate.alive=false;expect(b.respawnPlayer('SQUAD-1')).toBe(false);});
 it('deploys farther from attacked owned flags, but blocks recently firing squadmates',()=>{const b=make();isolate(b);const c=b.points[2]!;c.owner='blue';c.control=100;c.contested=true;die(b);expect(b.getDeploymentLocations().find(l=>l.id==='C')?.available).toBe(true);expect(b.respawnPlayer('C')).toBe(true);expect(Math.hypot(b.player.pos.x-c.x,b.player.pos.z-c.z)).toBeGreaterThanOrEqual(42);die(b);const mate=b.soldiers[1]!;mate.pos={x:0,z:0};mate.alertUntil=100;mate.state='ENGAGE';mate.suppression=.7;expect(b.respawnPlayer('SQUAD-1')).toBe(true);die(b);mate.combatUntil=8;expect(b.respawnPlayer('SQUAD-1')).toBe(false);});
 it('rejects foreign squad IDs, enemy flags and unsafe beacon deployment',()=>{const b=make();isolate(b);die(b);expect(b.respawnPlayer('SQUAD-4')).toBe(false);expect(b.respawnPlayer('C')).toBe(false);b.beacon={at:{x:0,z:0},expires:180};b.soldiers[8]!.pos={x:0,z:10};expect(b.respawnPlayer('BEACON')).toBe(false);expect(b.beacon).not.toBe(null);b.soldiers[8]!.pos={x:320,z:-300};expect(b.respawnPlayer('BEACON')).toBe(true);expect(b.beacon).toBe(null);});
});
describe('Class equipment affects the real battle',()=>{
 it('migrates saved equipment and binds each of four classes to its equipment',()=>{expect(validateLoadout({gadget:'repair'}).classId).toBe('engineer');expect(validateLoadout({gadget:'medkit'}).classId).toBe('medic');for(const [classId,c] of Object.entries(CLASSES))expect(validateLoadout({classId,gadget:'wrong'}).gadget).toBe(c.gadget);});
 it('medic revives an allied casualty without adding soldiers or replacing a respawn',()=>{const b=make();isolate(b);b.setLoadout({classId:'medic'});b.player.pos={x:0,z:0};const mate=b.soldiers[1]!;mate.pos={x:2,z:0};mate.alive=false;mate.deathAt=0;mate.respawnAt=7;expect(b.useGadget()).toBe(true);expect(mate.alive).toBe(true);expect(mate.hp).toBe(50);expect(b.soldiers).toHaveLength(16);expect(b.requisitionPoints).toBe(35);expect(b.events().some(e=>e.type==='revive')).toBe(true);});
 it('assault resupplies reserve only and recon places an expiring beacon',()=>{const b=make();isolate(b);b.player.pos={x:0,z:0};expect(b.useGadget()).toBe(false);for(let i=0;i<30;i++){b.shootPlayer({x:0,y:.1,z:1});run(b,.12);}b.startReload();run(b,2);const magazine=b.playerAmmo;expect(b.playerReserveAmmo).toBeLessThan(150);expect(b.useGadget()).toBe(true);expect(b.playerAmmo).toBe(magazine);expect(b.playerReserveAmmo).toBe(150);const r=make();isolate(r);r.setLoadout({classId:'recon'});r.player.pos={x:0,z:0};expect(r.useGadget()).toBe(true);expect(r.beacon?.expires).toBe(180);run(r,181);expect(r.beacon).toBe(null);});
 it('engineer rocket has travel time, damages armor and consumes finite ammunition',()=>{const b=make();isolate(b);b.setLoadout({classId:'engineer'});b.player.pos={x:0,z:0};const enemy=b.vehicles[1]!;enemy.pos={x:0,z:28};const hp=enemy.hp;expect(b.fireRocket({x:0,y:0,z:1})).toBe(true);expect(enemy.hp).toBe(hp);expect(b.rocketCount).toBe(1);expect(b.fireRocket({x:0,y:0,z:1})).toBe(false);run(b,.6);expect(enemy.hp).toBeLessThan(hp);expect(b.events().some(e=>e.type==='projectileImpact'&&e.kind==='rocket')).toBe(true);});
});
describe('Vehicle seats, actual shells and assisted driving',()=>{
 it('four seats isolate driving, MG and passengers; invalid seats do not change state',()=>{const b=make();isolate(b);const v=b.vehicles[0]!;v.pos={x:0,z:0};b.player.pos={x:0,z:9};expect(b.togglePlayerVehicle()).toBe(true);expect(b.switchVehicleSeat(2)).toBe(true);b.drivePlayerVehicle(1,1,.5);expect(v.pos).toEqual({x:0,z:0});expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(false);expect(b.switchVehicleSeat(4)).toBe(false);expect(b.playerSeat).toBe(2);expect(b.switchVehicleSeat(1)).toBe(true);expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(true);expect(b.events().some(e=>e.type==='vehicleShot'&&e.weapon==='mg')).toBe(true);expect(b.projectiles).toHaveLength(0);});
 it('shell damage is delayed until impact and wall collision prevents shooting through a building',()=>{const b=make();isolate(b);const v=b.vehicles[0]!,enemy=b.vehicles[1]!;v.pos={x:0,z:0};enemy.pos={x:0,z:28};b.player.pos={...v.pos};b.togglePlayerVehicle();const hp=enemy.hp;expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(true);expect(enemy.hp).toBe(hp);expect(b.projectiles).toHaveLength(1);run(b,.5);expect(enemy.hp).toBeLessThan(hp);
 const w=make();isolate(w);const car=w.vehicles[0]!,target=w.vehicles[1]!;car.pos={x:-315,z:-170};target.pos={x:-220,z:-170};w.player.pos={...car.pos};w.togglePlayerVehicle();const before=target.hp;w.shootPlayerVehicle({x:1,y:0,z:0});run(w,1);expect(target.hp).toBe(before);expect(w.events().some(e=>e.type==='projectileImpact')).toBe(true);});
 it('view-relative A/D moves toward the chosen side; brakes reduce speed and exit waits for AI',()=>{const b=make();isolate(b);const v=b.vehicles[0]!;v.pos={x:0,z:0};v.yaw=0;b.player.pos={...v.pos};b.togglePlayerVehicle();for(let i=0;i<120;i++)b.drivePlayerVehicle(0,1,1/60,0);expect(v.pos.x).toBeGreaterThan(1);expect(v.pos.z).toBeLessThan(8);const speed=v.speed;b.drivePlayerVehicle(1,0,.2,0,true);expect(v.speed).toBeLessThan(speed);expect(b.togglePlayerVehicle()).toBe(true);expect(v.driver).toBe(null);expect(v.nextDecision).toBeGreaterThan(b.elapsed);});
 it('adds a transport with an unarmed driver and armed gunner',()=>{const b=make();isolate(b);b.awardRP(500,'qa');expect(b.requestSupport('transport','C').ok).toBe(true);const v=b.vehicles.at(-1)!;run(b,8.1);b.player.pos={...v.pos};b.togglePlayerVehicle();expect(v.seatCount).toBe(4);expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(false);b.switchVehicleSeat(1);expect(b.shootPlayerVehicle({x:0,y:0,z:1})).toBe(true);});
});
describe('Slide and damage feedback',()=>{
 it('slide requires speed and respects cooldown, life and vehicle restrictions',()=>{const b=make();expect(b.startSlide({x:0,z:1},3)).toBe(false);expect(b.startSlide({x:0,z:1},8)).toBe(true);expect(b.sliding).toBe(true);expect(b.startSlide({x:0,z:1},8)).toBe(false);run(b,.8);expect(b.sliding).toBe(false);expect(b.startSlide({x:0,z:1},8)).toBe(false);run(b,1.5);expect(b.startSlide({x:0,z:1},8)).toBe(true);});
 it('real damage emits direction and amount rather than cosmetic-only flashes',()=>{const b=make();const attacker=b.soldiers[8]!;attacker.pos={x:10,z:0};(b as any).damage(b.player,20,attacker);expect(b.player.hp).toBe(80);expect(b.events()).toContainEqual({type:'playerHit',amount:20,from:{x:10,z:0},victim:0});});
});
describe('Breakthrough is a real alternative to Conquest',()=>{
 it('focuses squads on the active sector and advances through all five to victory',()=>{const b=new Battle({mode:'breakthrough',size:8,difficulty:'normal',tickets:100,seed:911});isolate(b);expect(b.points.every(p=>p.owner==='red')).toBe(true);expect(b.getSquadTargets().every(o=>o.objective==='A')).toBe(true);for(const p of b.points){b.player.pos={x:p.x,z:p.z};run(b,16);expect(p.owner).toBe('blue');}expect(b.sectorIndex).toBe(5);expect(b.finished).toBe(true);expect(b.winner).toBe('blue');});
 it('defenders win when attacker tickets expire; unrelated flags do not bleed tickets',()=>{const b=new Battle({mode:'breakthrough',size:8,difficulty:'normal',tickets:100,seed:911});isolate(b);run(b,2);expect(b.tickets.blue).toBe(100);b.tickets.blue=0;b.tick(.05);expect(b.finished).toBe(true);expect(b.winner).toBe('red');});
});
