import {describe,it,expect} from 'vitest';
import {Battle} from '../core/Battle';
import {heightAt} from '../core/math';
import {vehicleMuzzle} from '../vehicles/Vehicle';
const make=()=>new Battle({size:8,difficulty:'normal',tickets:500,seed:911});
const run=(b:Battle,t:number)=>{for(let i=0;i<t/.05;i++)b.tick(.05)};
describe('Actual occupants and player-reserved airdrops',()=>{
 it('empty vehicles remain stationary even if a legacy AI flag is set',()=>{const b=make();for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}const v=b.vehicles[0]!;v.driver='ai';v.nextDecision=0;const pos={...v.pos};run(b,2);expect(v.pos).toEqual(pos);expect(v.driver).toBe(null);});
 it('boards a real soldier, then dismounts that soldier when player takes control',()=>{const b=make(),v=b.vehicles[0]!,ai=b.soldiers[1]!;v.pos={x:0,z:0};v.nextDecision=0;ai.pos={x:0,z:3};for(const s of b.soldiers)if(s!==ai&&!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}b.tick(.05);expect(v.occupants[0]).toBe(ai.id);expect(ai.vehicleId).toBe(v.id);b.player.pos={x:0,z:5};expect(b.togglePlayerVehicle()).toBe(true);expect(v.occupants[0]).toBe(0);expect(ai.vehicleId).toBe(null);expect(ai.alive).toBe(true);expect(Math.hypot(ai.pos.x-v.pos.x,ai.pos.z-v.pos.z)).toBeGreaterThan(4);expect(b.switchVehicleSeat(1)).toBe(true);expect(v.occupants[0]).toBe(null);const before={...v.pos};b.drivePlayerVehicle(1,0,.5);run(b,1);expect(v.pos).toEqual(before);});
 it('airdrop cannot be entered early and AI never steals it after landing',()=>{const b=make();b.awardRP(9999,'test');expect(b.requestSupport('tank','C').ok).toBe(true);const v=b.vehicles.at(-1)!;b.player.pos={...v.pos};expect(b.togglePlayerVehicle()).toBe(false);run(b,8.1);expect(v.airborne).toBe(false);expect(v.reservedFor).toBe(0);const ai=b.soldiers[1]!;ai.pos={...v.pos};run(b,50);expect(v.driver).toBe(null);expect(v.occupants.every(x=>x===null)).toBe(true);expect(b.soldiers).toHaveLength(16);b.player.pos={...v.pos};expect(b.togglePlayerVehicle()).toBe(true);});
 it('shells spawn at the barrel endpoint and muzzle rays stop at nearby cover',()=>{const b=make(),v=b.vehicles[0]!;v.pos={x:0,z:0};b.player.pos={...v.pos};b.togglePlayerVehicle();b.shootPlayerVehicle({x:0,y:0,z:1});const muzzle=vehicleMuzzle(v);expect(b.projectiles[0]!.pos).toEqual({x:muzzle.x,y:heightAt(0,0)+muzzle.y,z:muzzle.z});expect(muzzle.z).toBeGreaterThan(5);b.togglePlayerVehicle();b.player.pos={x:0,z:-15};const origin={x:.25,y:heightAt(0,-15)+1.4,z:-16};expect(b.shootPlayer({x:0,y:0,z:1},1.78,origin)).toBe(true);const shot=b.events().find(e=>e.type==='shot'&&e.player);expect(shot&&'muzzle' in shot?shot.muzzle:null).toEqual(origin);});
});
