import {test,expect} from '@playwright/test';
import {existsSync} from 'node:fs';

test('menu exposes the required setup surfaces',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE_ERROR',e.message)});await page.goto('/');
 await expect(page.locator('#play')).toBeVisible();await expect(page.getByRole('button',{name:/战局|BATTLE/})).toBeVisible();
 await page.getByRole('button',{name:/画面|GRAPHICS/}).click();await expect(page.locator('#setup-quality')).toBeVisible();await expect(page.locator('#setup-fov')).toBeVisible();
 await page.getByRole('button',{name:/音频|AUDIO/}).click();await expect(page.locator('#setup-volume')).toBeVisible();
 await page.getByRole('button',{name:/操作|CONTROLS/}).click();await expect(page.locator('kbd').filter({hasText:'1 / 2'})).toBeVisible();expect(errors).toEqual([]);
});

test('starts a battle, shows HUD, pause and diagnostics',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE_ERROR',e.message)});await page.goto('/');
 await page.getByRole('button',{name:/战局|BATTLE/}).click();await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();
 await expect(page.locator('#battle-canvas')).toBeVisible();await expect(page.locator('#hud')).not.toHaveClass(/hidden/);await expect(page.locator('#player-stats')).toContainText(/HP/);
 await page.keyboard.press('F3');await expect(page.locator('#debug')).not.toHaveClass(/hidden/);await page.keyboard.press('Escape');await expect(page.locator('#resume')).toBeVisible();expect(errors).toEqual([]);
});

test('loadout persists, real RP support works, ADS fires and menu cleanup survives restart',async({page})=>{
 test.setTimeout(120_000);const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE_ERROR',e.message)});await page.setViewportSize({width:1440,height:1000});await page.goto('/');
 await page.locator('#loadout-primary').selectOption('sniper');await page.locator('#loadout-secondary').selectOption('pistol');await page.reload();await expect(page.locator('#loadout-primary')).toHaveValue('sniper');
 await page.locator('#setup-size').selectOption('32');await page.locator('#play').click();await expect(page.locator('#hud')).not.toHaveClass(/hidden/);await expect(page.locator('#player-stats')).toContainText('S12');
 await page.keyboard.press('Q');await expect(page.locator('[data-support]')).toHaveCount(8);await expect(page.locator('[data-support="tank"]')).toBeDisabled();await page.keyboard.press('Q');
 await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA; q.battle.awardRP(1500,'qa');});await page.keyboard.press('Q');await page.locator('#support-target').selectOption('C');await page.locator('[data-support="smoke"]').click();await page.locator('[data-support="tank"]').click();
 expect(await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;return {rp:b.requisitionPoints,smoke:b.supports.some((s:any)=>s.kind==='smoke'),vehicles:b.vehicles.length}})).toEqual({rp:950,smoke:true,vehicles:9});
 await page.screenshot({path:'test-results/support-menu.png'});await page.locator('#support-close').click();await page.waitForTimeout(1500);
 await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.world.weapon.aimBlend)).toBeGreaterThan(.9);await expect(page.locator('#hud')).toHaveClass(/scoped/);await page.screenshot({path:'test-results/sniper-ads.png'});
 const before=await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.playerAmmo);await page.mouse.down({button:'left'});await page.mouse.up({button:'left'});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.playerAmmo)).toBeLessThan(before);await page.mouse.up({button:'right'});
 await page.keyboard.press('M');await expect(page.locator('#tactical')).not.toHaveClass(/hidden/);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.locator('#quit').click();await expect(page.locator('#tactical')).toHaveClass(/hidden/);await expect(page.locator('#scoreboard')).toHaveClass(/hidden/);
 await page.locator('#play').click();await expect(page.locator('#hud')).not.toHaveClass(/hidden/);await page.waitForTimeout(1200);await expect(page.locator('#killfeed')).toBeEmpty();await page.screenshot({path:'test-results/battle-32v32.png'});
 // Headless frame pacing is a short QA sample, not a sustained interactive benchmark.
 const samples:number[]=[];for(let i=0;i<8;i++){await page.waitForTimeout(250);samples.push(await page.evaluate(()=>(window as any).__IRONFRONT_QA.fps));}
 const info=await page.evaluate(()=>{const w=(window as any).__IRONFRONT_QA.world;return {renderer:w.renderer.getContext().getParameter(w.renderer.getContext().RENDERER),calls:w.renderer.info.render.calls,ratio:w.renderer.getPixelRatio()}});console.log('HEADLESS_32V32_FPS',JSON.stringify({samples,info}));expect(errors).toEqual([]);
});

test('pointer-lock denial leaves drag look and weapon controls playable',async({page})=>{
 test.setTimeout(90_000);await page.addInitScript(()=>{HTMLCanvasElement.prototype.requestPointerLock=function(){return Promise.reject(new Error('QA denied'))}});await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await page.waitForTimeout(500);
 const before=await page.evaluate(()=>(window as any).__IRONFRONT_QA.world.camera.rotation.y);await page.mouse.move(700,450);await page.mouse.down({button:'right'});await page.mouse.move(750,450,{steps:5});await page.mouse.up({button:'right'});await page.waitForTimeout(200);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.world.camera.rotation.y)).not.toBe(before);await page.keyboard.press('Digit2');await expect(page.locator('#player-stats')).toContainText('M89');
});

test('A/D strafes without accumulated camera roll, Shift slides, damage direction and equipment stay visible',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('[data-class="engineer"]').click();await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.player.pos={x:0,z:0};for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles)v.nextDecision=1e9;});
 const before=await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA;return {yaw:q.world.camera.rotation.y,x:q.battle.player.pos.x,z:q.battle.player.pos.z}});
 await page.keyboard.down('KeyD');await page.waitForTimeout(2000);await page.keyboard.up('KeyD');
 const after=await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA;return {yaw:q.world.camera.rotation.y,roll:q.world.camera.rotation.z,x:q.battle.player.pos.x,z:q.battle.player.pos.z}});expect(after.yaw).toBeCloseTo(before.yaw,5);expect(Math.abs(after.roll)).toBeLessThan(.03);expect(Math.hypot(after.x-before.x,after.z-before.z)).toBeGreaterThan(5);expect((after.x-before.x)*Math.cos(before.yaw)-(after.z-before.z)*Math.sin(before.yaw)).toBeGreaterThan(5);await page.keyboard.down('KeyA');await page.waitForTimeout(1000);await page.keyboard.up('KeyA');const left=await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;return {x:b.player.pos.x,z:b.player.pos.z}});expect((left.x-after.x)*Math.cos(before.yaw)-(left.z-after.z)*Math.sin(before.yaw)).toBeLessThan(-3);
 await page.keyboard.down('KeyW');await page.waitForTimeout(400);await page.keyboard.press('Shift');await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.sliding)).toBe(true);await page.keyboard.up('KeyW');
 await expect(page.locator('#equipment-hud')).toContainText('反装甲火箭筒');await expect(page.locator('#equipment-hud')).toContainText('维修工具');await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.damage(b.player,18,b.soldiers[8]);});await expect(page.locator('#damage-direction')).not.toHaveClass(/hidden/);await expect(page.locator('#damage-amount')).toHaveText('−18 HP');await expect(page.locator('#player-stats')).toContainText('82');await page.screenshot({path:'test-results/damage-feedback.png'});expect(errors).toEqual([]);
});

test('driver shell, gunner MG, passengers and fourth transport are playable through keyboard controls',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles){v.nextDecision=1e9;}b.vehicles[0].pos={x:50,z:50};b.player.pos={x:50,z:59};});await page.keyboard.press('KeyE');await expect(page.locator('#equipment-hud')).toContainText('驾驶 / 主炮');await page.mouse.click(700,400);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.projectiles.length)).toBeGreaterThan(0);await page.screenshot({path:'test-results/vehicle-driver.png'});
 await page.keyboard.press('F3');await expect(page.locator('#equipment-hud .active-seat')).toContainText('成员位 1');const before=await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.vehicles[0].pos);await page.keyboard.down('KeyW');await page.waitForTimeout(300);await page.keyboard.up('KeyW');expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.vehicles[0].pos)).toEqual(before);
 await page.keyboard.press('F2');await expect(page.locator('#equipment-hud .active-seat')).toContainText('机枪位');await page.mouse.click(700,400);await page.screenshot({path:'test-results/vehicle-gunner.png'});await page.keyboard.press('KeyE');await expect(page.locator('#equipment-hud')).toContainText('突击兵');expect(errors).toEqual([]);
});

test('map deployment locks engaged squadmates and attacked flags and deploys beside a safe member',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1100});await page.goto('/');await page.locator('[data-class="medic"]').click();await page.locator('[data-weapon="smg"]').click();await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;s.combatUntil=0;s.alertUntil=0;s.suppression=0;s.state='DEFEND';}for(const v of b.vehicles)v.nextDecision=1e9;b.soldiers[1].pos={x:0,z:0};b.soldiers[2].pos={x:25,z:0};b.soldiers[2].combatUntil=1e8;b.points[2].owner='blue';b.points[2].control=100;b.points[2].contested=true;b.soldiers[8].pos={x:b.points[2].x+10,z:b.points[2].z};b.player.alive=false;b.player.deathAt=b.elapsed;b.player.respawnAt=b.elapsed+.3;});
 await expect(page.locator('#deployment-map')).toBeVisible();await page.locator('#deployment-locations [data-location="SQUAD-2"]').click();await expect(page.locator('#deploy-respawn')).toBeDisabled();await expect(page.locator('#deployment-locations [data-location="SQUAD-2"]')).toHaveClass(/blocked/);await page.locator('#deployment-locations [data-location="C"]').click();await expect(page.locator('#deploy-respawn')).toBeDisabled();await page.screenshot({path:'test-results/deployment-map.png',fullPage:true});await page.locator('.deployment-loadout').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/loadout-preparation.png',fullPage:true});
 await page.locator('#deployment-locations [data-location="SQUAD-1"]').click();await expect(page.locator('#deploy-respawn')).toBeEnabled();await page.locator('#deploy-respawn').click();await expect(page.locator('#deployment-map')).toHaveCount(0);expect(await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;return Math.hypot(b.player.pos.x-b.soldiers[1].pos.x,b.player.pos.z-b.soldiers[1].pos.z)})).toBeLessThan(7);await expect(page.locator('#equipment-hud')).toContainText('医疗兵');expect(errors).toEqual([]);
});

test('preparation selects and persists Breakthrough and the active frontline really advances',async({page})=>{
 await page.goto('/');await page.locator('#setup-mode').selectOption('breakthrough');await page.reload();await expect(page.locator('#setup-mode')).toHaveValue('breakthrough');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.settings.mode)).toBe('breakthrough');await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles)v.nextDecision=1e9;b.player.pos={x:b.points[0].x,z:b.points[0].z};b.points[0].control=99.9;});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.sectorIndex)).toBe(1);await expect(page.locator('#action-help')).toContainText('当前进攻 B');
});

test('local MP3 playback, decoded sound effects, mixing and result cues work',async({page})=>{
 test.skip(!existsSync('public/audio/music/main-theme.mp3'),'Import user-provided music to run the local MP3 integration check.');
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:/音频|AUDIO/}).click();await expect(page.locator('#setup-musicVolume')).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.decoded)).toBe(22);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.status)).toBe('playing');await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.slots.some((s:any)=>s.time>.1&&!s.paused))).toBe(true);
 await page.locator('#setup-musicVolume').fill('0');await page.waitForTimeout(100);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.slots.every((s:any)=>s.volume===0))).toBe(true);await page.locator('#setup-musicVolume').fill('36');await page.reload();await page.getByRole('button',{name:/音频|AUDIO/}).click();await expect(page.locator('#setup-musicVolume')).toHaveValue('36');await page.getByRole('button',{name:/战局|BATTLE/}).click();await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.track)).toBe('deployment');
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.nextAiAt=1e9;s.pos={x:320,z:-300};}for(const v of b.vehicles)v.nextDecision=1e9;b.elapsed=20;b.tickets.blue=80;});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.track),{timeout:12000}).toBe('critical');await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.finished=true;b.winner='blue';});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.track)).toBe('victory');console.log('AUDIO_QA',JSON.stringify(await page.evaluate(()=>(window as any).__IRONFRONT_QA.audio)));expect(errors).toEqual([]);
});

test('seven distinct first-person models render and missing music stays playable',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/audio/music/*.mp3',route=>route.fulfill({status:404,body:''}));await page.setViewportSize({width:1440,height:900});await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.nextAiAt=1e9;s.pos={x:320,z:-300};}for(const v of b.vehicles)v.nextDecision=1e9;b.player.pos={x:0,z:0};});
 const profiles:string[]=[];for(const id of ['carbine','marksman','smg','lmg','battleRifle','sniper','pistol']){await page.evaluate(id=>{const b=(window as any).__IRONFRONT_QA.battle;b.player.alive=false;b.setLoadout({primary:id==='pistol'?'carbine':id,secondary:'pistol'});b.player.alive=true;if(id==='pistol')b.switchPlayerWeapon('pistol');},id);await page.waitForTimeout(500);const profile=await page.evaluate(()=>{const g=(window as any).__IRONFRONT_QA.world.weapon.group;return g.children.filter((c:any)=>c.visible&&c.name.startsWith('weapon-')).map((c:any)=>c.userData.profile)[0]});profiles.push(profile);await page.screenshot({path:`test-results/weapon-${id}.png`});}expect(new Set(profiles).size).toBe(7);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.status)).toBe('missing');await expect(page.locator('#hud')).not.toHaveClass(/hidden/);expect(errors).toEqual([]);
});
