import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
async function readySolo(page:Page){await page.locator('#ready').click();await expect(page.locator('.entry-caption')).toBeVisible();await expect(page.locator('#modal')).toHaveClass('hidden');}
async function readyLan(page:Page,host=false){await page.locator('#ready').click();if(host){await expect(page.locator('#begin-match')).toBeEnabled();await page.locator('#begin-match').click();}await expect(page.locator('#modal')).toHaveClass('hidden');}
import {existsSync} from 'node:fs';

test('menu exposes the required setup surfaces',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE_ERROR',e.message)});await page.goto('/');
 await expect(page.locator('#play')).toBeVisible();await page.screenshot({path:'test-results/operator-menu-010.png'});await expect(page.getByRole('button',{name:/战局|BATTLE/})).toBeVisible();
 await page.getByRole('button',{name:/画面|GRAPHICS/}).click();await expect(page.locator('#setup-quality')).toBeVisible();await expect(page.locator('#setup-fov')).toBeVisible();
 await page.getByRole('button',{name:/音频|AUDIO/}).click();await expect(page.locator('#setup-volume')).toBeVisible();
 await page.getByRole('button',{name:/操作|CONTROLS/}).click();await expect(page.locator('kbd').filter({hasText:'1 / 2'})).toBeVisible();expect(errors).toEqual([]);
});

test('starts a battle, shows HUD, pause and diagnostics',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE_ERROR',e.message)});await page.goto('/');
 await page.getByRole('button',{name:/战局|BATTLE/}).click();await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);
 await expect(page.locator('#battle-canvas')).toBeVisible();await expect(page.locator('#hud')).not.toHaveClass(/hidden/);await expect(page.locator('#player-stats')).toContainText(/HP/);
 await page.keyboard.press('F3');await expect(page.locator('#debug')).not.toHaveClass(/hidden/);await page.keyboard.press('Escape');await expect(page.locator('#resume')).toBeVisible();expect(errors).toEqual([]);
});

test('loadout persists, real RP support works, ADS fires and menu cleanup survives restart',async({page})=>{
 test.setTimeout(120_000);const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE_ERROR',e.message)});await page.setViewportSize({width:1440,height:1000});await page.goto('/');
 await page.locator('#play').click();await page.locator('[data-weapon=sniper]').click();await page.locator('[data-slot=secondary]').click();await page.locator('[data-weapon=pistol]').click();await page.reload();
 await page.locator('#setup-size').selectOption('32');await page.locator('#play').click();await readySolo(page);await expect(page.locator('#hud')).not.toHaveClass(/hidden/);await expect(page.locator('#player-stats')).toContainText('S12');
 await page.keyboard.press('Q');await expect(page.locator('[data-support]')).toHaveCount(12);await expect(page.locator('[data-support="tank"]')).toBeDisabled();await page.keyboard.press('Q');
 await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA; q.battle.settings.vehicleLimit=20;q.battle.awardRP(1500,'qa');});await page.keyboard.press('Q');await page.locator('#support-target').selectOption('C');await page.locator('[data-support="smoke"]').click();await page.locator('[data-support="tank"]').click();
 expect(await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;return {rp:b.requisitionPoints,smoke:b.supports.some((s:any)=>s.kind==='smoke'),vehicles:b.vehicles.length}})).toEqual({rp:950,smoke:true,vehicles:17});
 await page.screenshot({path:'test-results/support-menu.png'});await page.locator('#support-close').click();await page.waitForTimeout(1500);
 await page.mouse.down({button:'right'});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.world.weapon.aimBlend)).toBeGreaterThan(.9);await expect(page.locator('#hud')).toHaveClass(/scoped/);await page.screenshot({path:'test-results/sniper-ads.png'});
 const before=await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.playerAmmo);await page.mouse.down({button:'left'});await page.mouse.up({button:'left'});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.playerAmmo)).toBeLessThan(before);await page.mouse.up({button:'right'});
 await page.keyboard.press('M');await expect(page.locator('#tactical')).not.toHaveClass(/hidden/);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.locator('#quit').click();await expect(page.locator('#tactical')).toHaveClass(/hidden/);await expect(page.locator('#scoreboard')).toHaveClass(/hidden/);
 await page.locator('#play').click();await readySolo(page);await expect(page.locator('#hud')).not.toHaveClass(/hidden/);await page.waitForTimeout(1200);await expect(page.locator('#killfeed')).toBeEmpty();await page.screenshot({path:'test-results/battle-32v32.png'});
 // Headless frame pacing is a short QA sample, not a sustained interactive benchmark.
 const samples:number[]=[];for(let i=0;i<8;i++){await page.waitForTimeout(250);samples.push(await page.evaluate(()=>(window as any).__IRONFRONT_QA.fps));}
 const info=await page.evaluate(()=>{const w=(window as any).__IRONFRONT_QA.world;return {renderer:w.renderer.getContext().getParameter(w.renderer.getContext().RENDERER),calls:w.renderer.info.render.calls,ratio:w.renderer.getPixelRatio()}});console.log('HEADLESS_32V32_FPS',JSON.stringify({samples,info}));expect(errors).toEqual([]);
});

test('pointer-lock denial leaves drag look and weapon controls playable',async({page})=>{
 test.setTimeout(90_000);await page.addInitScript(()=>{HTMLCanvasElement.prototype.requestPointerLock=function(){return Promise.reject(new Error('QA denied'))}});await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);await page.waitForTimeout(500);
 const before=await page.evaluate(()=>(window as any).__IRONFRONT_QA.world.camera.rotation.y);await page.mouse.move(700,450);await page.mouse.down({button:'right'});await page.mouse.move(750,450,{steps:5});await page.mouse.up({button:'right'});await page.waitForTimeout(200);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.world.camera.rotation.y)).not.toBe(before);await page.keyboard.press('Digit2');await expect(page.locator('#player-stats')).toContainText('M89');
});

test('A/D strafes without accumulated camera roll, Shift slides, damage direction and equipment stay visible',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await page.locator('[data-class="engineer"]').click();await readySolo(page);
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.player.pos={x:0,z:0};for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles)v.nextDecision=1e9;});
 const before=await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA;return {yaw:q.world.camera.rotation.y,x:q.battle.player.pos.x,z:q.battle.player.pos.z}});
 await page.keyboard.down('KeyD');await page.waitForTimeout(2000);await page.keyboard.up('KeyD');
 const after=await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA;return {yaw:q.world.camera.rotation.y,roll:q.world.camera.rotation.z,x:q.battle.player.pos.x,z:q.battle.player.pos.z}});expect(after.yaw).toBeCloseTo(before.yaw,5);expect(Math.abs(after.roll)).toBeLessThan(.03);expect(Math.hypot(after.x-before.x,after.z-before.z)).toBeGreaterThan(5);expect((after.x-before.x)*Math.cos(before.yaw)-(after.z-before.z)*Math.sin(before.yaw)).toBeGreaterThan(5);await page.keyboard.down('KeyA');await page.waitForTimeout(1000);await page.keyboard.up('KeyA');const left=await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;return {x:b.player.pos.x,z:b.player.pos.z}});expect((left.x-after.x)*Math.cos(before.yaw)-(left.z-after.z)*Math.sin(before.yaw)).toBeLessThan(-3);
 await page.keyboard.down('KeyW');await page.waitForTimeout(400);await page.keyboard.press('Shift');await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.sliding)).toBe(true);await page.keyboard.up('KeyW');
 await expect(page.locator('#equipment-hud')).toContainText('反装甲火箭筒');await expect(page.locator('#equipment-hud')).toContainText('维修工具');await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.damage(b.player,18,b.soldiers[8]);});await expect(page.locator('#damage-direction')).not.toHaveClass(/hidden/);await expect(page.locator('#damage-amount')).toHaveText('−18 HP');await expect(page.locator('#player-stats')).toContainText('82');await page.screenshot({path:'test-results/damage-feedback.png'});expect(errors).toEqual([]);
});

test('driver shell, gunner MG, passengers and fourth transport are playable through keyboard controls',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles){v.nextDecision=1e9;}b.vehicles[0].pos={x:50,z:50};b.player.pos={x:50,z:59};});await page.keyboard.press('KeyE');await expect(page.locator('#equipment-hud')).toContainText('驾驶 / 主炮');await page.evaluate(()=>{const w=(window as any).__IRONFRONT_QA.world,original=w.showEvents.bind(w);(window as any).__driverShellSeen=false;w.showEvents=(events:any[],...rest:any[])=>{if(events.some(e=>e.type==='vehicleShot'&&e.player&&e.weapon==='shell'))(window as any).__driverShellSeen=true;return original(events,...rest);};});await page.mouse.click(700,400);await expect.poll(()=>page.evaluate(()=>(window as any).__driverShellSeen)).toBe(true);await page.screenshot({path:'test-results/vehicle-driver.png'});
 await page.keyboard.press('F3');await expect(page.locator('#equipment-hud .active-seat')).toContainText('成员位 1');const before=await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.vehicles[0].pos);await page.keyboard.down('KeyW');await page.waitForTimeout(300);await page.keyboard.up('KeyW');expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.vehicles[0].pos)).toEqual(before);
 await page.keyboard.press('F2');await expect(page.locator('#equipment-hud .active-seat')).toContainText('机枪位');await page.mouse.click(700,400);await page.screenshot({path:'test-results/vehicle-gunner.png'});await page.keyboard.press('KeyE');await expect(page.locator('#equipment-hud')).toContainText('突击兵');expect(errors).toEqual([]);
});

test('map deployment blocks engaged squadmates and offers distant attacked flags and deploys beside a safe member',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1100});await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await page.locator('[data-class="medic"]').click();await page.locator('[data-weapon="smg"]').click();await readySolo(page);
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;s.combatUntil=0;s.alertUntil=0;s.suppression=0;s.state='DEFEND';}for(const v of b.vehicles)v.nextDecision=1e9;b.soldiers[1].pos={x:0,z:0};b.soldiers[2].pos={x:25,z:0};b.soldiers[2].combatUntil=1e8;b.points[2].owner='blue';b.points[2].control=100;b.points[2].contested=true;b.soldiers[8].pos={x:b.points[2].x+10,z:b.points[2].z};b.player.alive=false;b.player.deathAt=b.elapsed;b.player.respawnAt=b.elapsed+.3;});
 await expect(page.locator('#deployment-map')).toBeVisible();await page.locator('#deployment-locations [data-location="SQUAD-2"]').click();await expect(page.locator('#deploy-respawn')).toBeDisabled();await expect(page.locator('#deployment-locations [data-location="SQUAD-2"]')).toHaveClass(/blocked/);await page.locator('#deployment-locations [data-location="C"]').click();await expect(page.locator('#deploy-respawn')).toBeEnabled();await page.screenshot({path:'test-results/deployment-map.png',fullPage:true});await page.locator('.deployment-loadout').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/loadout-preparation.png',fullPage:true});
 await page.locator('#deployment-locations [data-location="SQUAD-1"]').click();await expect(page.locator('#deploy-respawn')).toBeEnabled();await page.locator('#deploy-respawn').click();await expect(page.locator('#deployment-map')).toHaveCount(0);expect(await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;return Math.hypot(b.player.pos.x-b.soldiers[1].pos.x,b.player.pos.z-b.soldiers[1].pos.z)})).toBeLessThan(7);await expect(page.locator('#equipment-hud')).toContainText('医疗兵');expect(errors).toEqual([]);
});

test('preparation selects and persists Breakthrough and the active frontline really advances',async({page})=>{
 await page.goto('/');await page.locator('#setup-mode').selectOption('breakthrough');await page.reload();await expect(page.locator('#setup-mode')).toHaveValue('breakthrough');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.settings.mode)).toBe('breakthrough');await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles)v.nextDecision=1e9;b.player.pos={x:b.points[0].x,z:b.points[0].z};b.points[0].control=99.9;});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.sectorIndex)).toBe(1);await expect(page.locator('#action-help')).toContainText('当前进攻 B');
});

test('local MP3 playback, decoded sound effects, mixing and result cues work',async({page})=>{
 test.skip(!existsSync('public/audio/music/main-theme.mp3'),'Import user-provided music to run the local MP3 integration check.');
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:/音频|AUDIO/}).click();await expect(page.locator('#setup-musicVolume')).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.decoded)).toBe(29);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.status)).toBe('playing');await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.slots.some((s:any)=>s.time>.1&&!s.paused))).toBe(true);
 await page.locator('#setup-musicVolume').fill('0');await page.waitForTimeout(100);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.slots.every((s:any)=>s.volume===0))).toBe(true);await page.locator('#setup-musicVolume').fill('36');await page.reload();await page.getByRole('button',{name:/音频|AUDIO/}).click();await expect(page.locator('#setup-musicVolume')).toHaveValue('36');await page.getByRole('button',{name:/战局|BATTLE/}).click();await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.track)).toBe('deployment');
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.nextAiAt=1e9;s.pos={x:320,z:-300};}for(const v of b.vehicles)v.nextDecision=1e9;b.elapsed=20;b.tickets.blue=80;});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.track),{timeout:12000}).toBe('critical');await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.finished=true;b.winner='blue';});await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.track)).toBe('victory');console.log('AUDIO_QA',JSON.stringify(await page.evaluate(()=>(window as any).__IRONFRONT_QA.audio)));expect(errors).toEqual([]);
});

test('seven distinct first-person models render and missing music stays playable',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/audio/music/*.mp3',route=>route.fulfill({status:404,body:''}));await page.setViewportSize({width:1440,height:900});await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.nextAiAt=1e9;s.pos={x:320,z:-300};}for(const v of b.vehicles)v.nextDecision=1e9;b.player.pos={x:0,z:0};});
 const profiles:string[]=[];for(const id of ['carbine','marksman','smg','lmg','battleRifle','sniper','pistol']){await page.evaluate(id=>{const b=(window as any).__IRONFRONT_QA.battle;b.player.alive=false;b.setLoadout({primary:id==='pistol'?'carbine':id,secondary:'pistol'});b.player.alive=true;if(id==='pistol')b.switchPlayerWeapon('pistol');},id);await page.waitForTimeout(500);const profile=await page.evaluate(()=>{const g=(window as any).__IRONFRONT_QA.world.weapon.group;return g.children.filter((c:any)=>c.visible&&c.name.startsWith('weapon-')).map((c:any)=>c.userData.profile)[0]});profiles.push(profile);await page.screenshot({path:`test-results/weapon-${id}.png`});}expect(new Set(profiles).size).toBe(7);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.audio.music.status)).toBe('missing');await expect(page.locator('#hud')).not.toHaveClass(/hidden/);expect(errors).toEqual([]);
});

test('airdrop reserves armor for caller and actual driver exits on takeover',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.player.pos={x:0,z:-30};for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles)v.nextDecision=1e9;b.settings.vehicleLimit=20;b.awardRP(9999,'QA');b.requestSupport('tank','C');});
 expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.vehicles.at(-1).airborne)).toBe(true);await page.waitForTimeout(1200);await page.screenshot({path:'test-results/airdrop-inbound.png'});
 await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.vehicles.at(-1).airborne),{timeout:15000}).toBe(false);
 const result=await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA,b=q.battle,v=b.vehicles.at(-1),ai=b.soldiers[1];ai.pos={...v.pos};v.nextDecision=0;b.tick(.1);const reserved=v.driver===null;b.player.pos={...v.pos};const entered=b.togglePlayerVehicle();const pos={...v.pos};b.drivePlayerVehicle(1,0,.5);return {reserved,entered,moved:Math.hypot(v.pos.x-pos.x,v.pos.z-pos.z)>0,occupant:v.occupants[0]};});expect(result).toEqual({reserved:true,entered:true,moved:true,occupant:0});await page.screenshot({path:'test-results/airdrop-driving.png'});expect(errors).toEqual([]);
});

test('death falls then rises into deployment instead of opening map immediately',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.player.pos={x:0,z:0};b.player.alive=false;b.player.hp=0;b.player.deathAt=b.elapsed;b.player.respawnAt=b.elapsed+4.5;});
 await expect(page.locator('.death-caption')).toBeVisible();await expect(page.locator('#deployment-map')).toHaveCount(0);await page.waitForTimeout(900);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.world.camera.position.y)).toBeLessThan(15);await page.screenshot({path:'test-results/death-fall.png'});
 await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.world.camera.position.y)).toBeGreaterThan(100);await page.screenshot({path:'test-results/death-rise.png'});await expect(page.locator('#deployment-map')).toBeVisible();await page.waitForTimeout(850);await page.screenshot({path:'test-results/deployment-090.png'});expect(errors).toEqual([]);
});

test('player shot event uses the rendered muzzle and damage flashes immediately',async({page})=>{
 await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);
 await page.evaluate(()=>{(window as any).__IRONFRONT_QA.battle.player.pos={x:0,z:0};});await page.waitForTimeout(150);
 const shot=await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA,b=q.battle,w=q.world;const m=w.weapon.muzzleWorldPosition();b.playerNextShot=0;b.shootPlayer({x:0,y:0,z:-1},1.78,m);const e=b.events().find((x:any)=>x.type==='shot'&&x.player);b.damage(b.player,32,b.soldiers[8]);return {muzzle:e?.muzzle,model:{x:m.x,y:m.y,z:m.z}};});
 expect(shot.muzzle).toEqual(shot.model);await expect(page.locator('#damage-direction')).not.toHaveClass(/hidden/);await expect.poll(()=>page.locator('#damage-vignette').evaluate(el=>Number(getComputedStyle(el).opacity))).toBeGreaterThan(.45);await page.screenshot({path:'test-results/injury-090.png'});
});

test('vehicle RMB optics, independent MG model, capture progress, Esc resume and unstuck work',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(!s.player){s.pos={x:320,z:-300};s.nextAiAt=1e9;}for(const v of b.vehicles)v.nextDecision=1e9;b.vehicles[0].pos={x:0,z:0};b.player.pos={x:0,z:8};});
 await page.keyboard.press('E');await page.mouse.down({button:'right'});await expect(page.locator('#hud')).toHaveClass(/vehicle-optics/);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.world.camera.fov)).toBeLessThan(35);await page.screenshot({path:'test-results/vehicle-optics-010.png'});await page.mouse.up({button:'right'});await page.keyboard.press('F2');await expect(page.locator('#equipment-hud')).toContainText('机枪位');await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.world.equipment.root.visible)).toBe(true);await page.screenshot({path:'test-results/mounted-mg-010.png'});
 await page.keyboard.press('E');await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;b.player.pos={x:b.points[2].x,z:b.points[2].z};b.points[2].control=50;});await expect(page.locator('#capture-progress')).toContainText('%');await page.screenshot({path:'test-results/capture-hud-010.png'});
 await page.keyboard.press('Escape');await expect(page.locator('#resume')).toBeVisible();await page.waitForTimeout(200);await page.keyboard.press('Escape');await expect(page.locator('#resume')).not.toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#unstuck')).toBeVisible();await page.locator('#unstuck').click();await expect(page.locator('#resume')).not.toBeVisible();expect(errors).toEqual([]);
});

test('LAN menu hosts and joins one authoritative room from two browser clients',async({browser})=>{
 const context=await browser.newContext(),a=await context.newPage(),b=await context.newPage();const errors:string[]=[];for(const page of [a,b])page.on('pageerror',e=>errors.push(e.message));
 try{await a.goto('/');await a.locator('#lan-ai').uncheck();await a.locator('#lan-address').fill('127.0.0.1:18788');await a.locator('#lan-host').click();await readyLan(a,true);await expect(a.locator('#lan-hud')).toContainText('LAN');const code=(await a.locator('#lan-hud').innerText()).split(' ')[1]!;
 await b.goto('/');await b.locator('#lan-address').fill('127.0.0.1:18788');await b.locator('#lan-code').fill(code);await b.locator('#lan-join').click();await readyLan(b);await expect(b.locator('#lan-hud')).toContainText(code);
 const ids=await Promise.all([a,b].map(p=>p.evaluate(()=>(window as any).__IRONFRONT_QA.battle.player.id)));expect(ids[0]).not.toBe(ids[1]);const initial=await b.evaluate(id=>(window as any).__IRONFRONT_QA.battle.soldiers[id!].pos.x,ids[0]);await a.bringToFront();if(await a.locator('#resume').isVisible())await a.locator('#resume').click();await a.keyboard.down('D');await a.waitForTimeout(700);await a.keyboard.up('D');await expect.poll(()=>b.evaluate(id=>(window as any).__IRONFRONT_QA.battle.soldiers[id!].pos.x,ids[0])).not.toBe(initial);await a.screenshot({path:'test-results/lan-host-010.png'});expect(errors).toEqual([]);
 }finally{await context.close();}
});

test('host configures AI-free opposing teams and changes a joining player faction',async({browser})=>{
 const context=await browser.newContext(),a=await context.newPage(),b=await context.newPage();try{await a.goto('/');await a.locator('#setup-size').selectOption('8');await a.locator('#lan-address').fill('127.0.0.1:18788');await a.locator('#lan-ai').uncheck();await a.locator('#lan-team').selectOption('red');await a.locator('#lan-host').click();await readyLan(a,true);await expect(a.locator('#lan-hud')).toContainText('LAN');const code=(await a.locator('#lan-hud').innerText()).split(' ')[1]!;await b.goto('/');await b.locator('#lan-address').fill('127.0.0.1:18788');await b.locator('#lan-code').fill(code);await b.locator('#lan-join').click();await readyLan(b);await expect(b.locator('#lan-hud')).toContainText(code);expect(await b.evaluate(()=>(window as any).__IRONFRONT_QA.battle.player.team)).toBe('red');expect(await b.evaluate(()=>(window as any).__IRONFRONT_QA.battle.soldiers.filter((s:any)=>s.alive).length)).toBe(2);const id=await b.evaluate(()=>(window as any).__IRONFRONT_QA.battle.player.id);await a.bringToFront();if(!(await a.locator('[data-player-team]').count())){if(await a.locator('#resume').isVisible())await a.locator('#resume').click();await a.keyboard.press('Escape');}await expect(a.locator(`[data-player-team="${id}"]`)).toBeVisible();await a.locator(`[data-player-team="${id}"]`).selectOption('blue');await expect.poll(()=>b.evaluate(()=>(window as any).__IRONFRONT_QA.battle.player.team)).toBe('blue');await a.screenshot({path:'test-results/host-factions-010.png'});}finally{await context.close();}
});

test('deployment selects a real free vehicle seat and block characters distinguish humans and teams',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA,b=q.battle,w=q.world;b.player.pos={x:0,z:0};});
 // Place frozen figures in front of the actual camera without modifying look controls.
 await page.evaluate(()=>{const q=(window as any).__IRONFRONT_QA,b=q.battle;const yaw=q.world.camera.rotation.y,fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);for(const s of b.soldiers)if(s.id!==b.player.id){s.nextAiAt=1e9;s.pos={x:320,z:-300};s.alive=false;}for(const [i,id] of [1,2,8,9].entries()){const s=b.soldiers[id];s.alive=true;s.vehicleId=null;s.pos={x:fx*7+rx*(i-1.5)*2,z:fz*7+rz*(i-1.5)*2};s.yaw=yaw;s.player=i%2===1;s.deathAt=-999;}for(const v of b.vehicles)v.nextDecision=1e9;});await page.waitForTimeout(350);await page.screenshot({path:'test-results/block-factions-010.png'});
 await page.evaluate(()=>{const b=(window as any).__IRONFRONT_QA.battle;for(const s of b.soldiers)if(s.id!==b.player.id){s.alive=false;s.nextAiAt=1e9;s.respawnAt=1e9;}const v=b.vehicles[0];v.pos={x:0,z:0};v.occupants.fill(null);v.combatUntil=0;b.player.alive=false;b.player.deathAt=b.elapsed;b.player.respawnAt=b.elapsed;});await expect(page.locator('#deployment-map')).toBeVisible();await page.locator('#deployment-locations [data-location="VEHICLE-0-1"]').click();await expect(page.locator('#deploy-respawn')).toBeEnabled();await page.locator('#deploy-respawn').click();await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.playerSeat)).toBe(1);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.inVehicle)).toBe(true);expect(errors).toEqual([]);
});

test('solo entry works without creating or joining a network room',async({page})=>{
 let roomRequests=0;page.on('request',r=>{if(r.url().includes('/api/rooms'))roomRequests++;});await page.goto('/');await expect(page.locator('#play')).toContainText('单人游戏');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await readySolo(page);await expect(page.locator('#hud')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.network-info')).toContainText('无需连接房间');expect(roomRequests).toBe(0);
});

test('LAN settings expose address port and code while walking remains continuous between snapshots',async({page})=>{
 await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#lan-address').fill('127.0.0.1:18788');await page.locator('#lan-ai').uncheck();await page.locator('#lan-host').click();await readyLan(page,true);await expect(page.locator('#lan-hud')).toContainText('LAN');await page.keyboard.press('Escape');await expect(page.locator('#connection-address')).toContainText('127.0.0.1:18788');await expect(page.locator('#connection-code')).toHaveText(/[A-Z0-9]{6}/);await page.screenshot({path:'test-results/connection-settings-011.png'});await page.locator('#resume').click();
 await page.keyboard.down('D');const samples=await page.evaluate(()=>new Promise<{x:number,z:number}[]>(resolve=>{const values:{x:number,z:number}[]=[];function sample(){const p=(window as any).__IRONFRONT_QA.battle.player.pos;values.push({...p});if(values.length<80)requestAnimationFrame(sample);else resolve(values);}requestAnimationFrame(sample);}));await page.keyboard.up('D');const deltas=samples.slice(9).map((p,i)=>Math.hypot(p.x-samples[i+8].x,p.z-samples[i+8].z));const stationary=deltas.filter(d=>d<.001).length/deltas.length;console.log('LAN_WALK_CONTINUITY',JSON.stringify({stationaryFraction:stationary,maxFrameStep:Math.max(...deltas),samples:80}));expect(stationary).toBeLessThan(.2);expect(Math.max(...deltas)).toBeLessThan(.7);
});

test('equipment keys draw models without spending charges and left click uses the selected item',async({page})=>{
 await page.goto('/');await page.locator('#setup-size').selectOption('8');await page.locator('#play').click();await page.locator('[data-class="engineer"]').click();await readySolo(page);
 await page.keyboard.press('G');await expect(page.locator('#equipment-hud')).toContainText('破片手雷');expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.grenadeCount)).toBe(2);await page.mouse.click(500,400);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.grenadeCount)).toBe(1);await page.waitForTimeout(1200);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.world.equipment.root.visible)).toBe(true);
 await page.keyboard.press('Z');await expect(page.locator('.equipment-icon[title="反装甲火箭筒"]')).toHaveClass(/selected/);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.rocketCount)).toBe(2);await page.mouse.click(500,400);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.rocketCount)).toBe(1);await page.screenshot({path:'test-results/equipment-held-012.png'});await page.keyboard.press('Digit1');await expect(page.locator('#equipment-hud')).not.toContainText('当前：');await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.world.equipment.root.visible)).toBe(false);
});

test('real LAN IP hosts and share link joins without manually correcting host address or port',async({browser,request})=>{
 const info=await (await request.get('http://127.0.0.1:18788/api/status')).json();expect(info.addresses.length).toBeGreaterThan(0);const base=info.addresses[0],context=await browser.newContext(),a=await context.newPage(),b=await context.newPage();
 try{await a.goto(base);await expect(a.locator('#lan-address')).toHaveValue(new URL(base).host);await a.locator('#setup-size').selectOption('8');await a.locator('#lan-ai').uncheck();await a.locator('#lan-host').click();await readyLan(a,true);await expect(a.locator('#lan-hud')).toContainText('LAN');const code=(await a.locator('#lan-hud').innerText()).split(' ')[1]!;
 await b.goto(`${base}/?room=${code}`);await expect(b.locator('#lan-code')).toHaveValue(code);await b.locator('#lan-join').click();await readyLan(b);await expect(b.locator('#lan-hud')).toContainText(code);await a.keyboard.press('Escape');await expect(a.locator('.share-address').first()).toContainText(`?room=${code}`);await a.screenshot({path:'test-results/lan-share-012.png'});
 }finally{await context.close();}
});

test('LAN connection diagnostics distinguish invalid rooms from unreachable services',async({page})=>{
 await page.goto('/');await page.locator('#lan-address').fill('127.0.0.1:18788');await page.locator('#lan-probe').click();await expect(page.locator('#lan-status')).toContainText('服务可达');await page.locator('#lan-code').fill('ZZZZZZ');await page.locator('#lan-join').click();await expect(page.locator('#lan-status')).toContainText('房间码不存在');await page.locator('#lan-address').fill('127.0.0.1:18789');await page.locator('#lan-probe').click();await expect(page.locator('#lan-status')).toContainText('无法访问');
});

for(const network of [false,true])test(`${network?'LAN':'solo'} tracers remain attached to the visible muzzle while walking and aiming`,async({page})=>{
 await page.goto('/');await page.locator('#setup-size').selectOption('8');if(network){await page.locator('#lan-address').fill('127.0.0.1:18788');await page.locator('#lan-ai').uncheck();await page.locator('#lan-host').click();await readyLan(page,true);await expect(page.locator('#lan-hud')).toContainText('LAN');}else {await page.locator('#play').click();await readySolo(page);}await page.keyboard.down('D');await page.mouse.down({button:'right'});await page.mouse.down({button:'left'});
 const error=await page.evaluate(()=>new Promise<{error:number,count:number}>(resolve=>{let max=0,n=0,count=0;function sample(){const q=(window as any).__IRONFRONT_QA,w=q.world,m=w.weapon.muzzleWorldPosition();for(const t of w.tracer.filter((t:any)=>t.followMuzzle)){const p=t.line.geometry.getAttribute('position');count++;max=Math.max(max,Math.hypot(p.getX(0)-m.x,p.getY(0)-m.y,p.getZ(0)-m.z));}if(++n<40)requestAnimationFrame(sample);else resolve({error:max,count});}requestAnimationFrame(sample);}));await page.keyboard.up('D');await page.mouse.up({button:'left'});await page.mouse.up({button:'right'});expect(error.count).toBeGreaterThan(0);expect(error.error).toBeLessThan(.001);
});


test('LAN equipment selection is nonconsuming and only a click sends a weapon action',async({page})=>{
 await page.goto('/');await page.evaluate(()=>localStorage.setItem('ironfront-loadout',JSON.stringify({classId:'engineer'})));await page.reload();await page.locator('#setup-size').selectOption('8');await page.locator('#lan-address').fill('127.0.0.1:18788');await page.locator('#lan-ai').uncheck();await page.locator('#lan-host').click();await readyLan(page,true);await expect(page.locator('#lan-hud')).toContainText('LAN');await page.keyboard.press('Z');await expect(page.locator('.equipment-icon[title="反装甲火箭筒"]')).toHaveClass(/selected/);await page.waitForTimeout(250);expect(await page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.rocketCount)).toBe(2);await page.mouse.click(500,400);await expect.poll(()=>page.evaluate(()=>(window as any).__IRONFRONT_QA.battle.rocketCount)).toBe(1);await page.keyboard.press('Digit1');await expect(page.locator('#equipment-hud')).not.toContainText('当前：');
});


test('an old host process is rejected before creating an incompatible room',async({page})=>{
 await page.route('**/api/status',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({version:'0.11.0',port:18788,addresses:[],rooms:[]})}));await page.goto('/');await page.locator('#lan-address').fill('127.0.0.1:18788');await page.locator('#lan-host').click();await expect(page.locator('#lan-status')).toContainText('版本 0.11.0');await expect(page.locator('#lan-status')).toContainText('停止旧进程');
});
