import type {Battle,BattleSettings,BattleEvent} from '../core/Battle';
import {MAP_SIZE,BASES,type Team} from '../world/Layout';
import {WEAPONS,WEAPON_ORDER,validateLoadout,type Loadout} from '../combat/Weapons';
import {SUPPORTS,type SupportId} from '../gameplay/Requisition';
import {VEHICLE_TYPES} from '../vehicles/Vehicle';
import {dist} from '../core/math';
export type Lang='en'|'zh';
export type GraphicsQuality='low'|'medium'|'high';
export interface GameOptions extends BattleSettings {language:Lang;quality:GraphicsQuality;sensitivity:number;volume:number;fov:number;killTicketPenalty:number;renderScale:number}
export const defaults:GameOptions={size:32,difficulty:'normal',tickets:500,killTicketPenalty:1,language:'zh',quality:'high',sensitivity:.22,volume:.4,fov:79,renderScale:1};
export function savedOptions():GameOptions{
 try{const data=JSON.parse(localStorage.getItem('ironfront-options')||'{}') as Partial<GameOptions>;const result={...defaults,...data};
  if(![8,16,32,64].includes(result.size))result.size=32;if(![300,500,800].includes(result.tickets))result.tickets=500;
  if(!['easy','normal','hard'].includes(result.difficulty))result.difficulty='normal';if(!['en','zh'].includes(result.language))result.language='zh';
  if(!['low','medium','high'].includes(result.quality))result.quality='high';if(![0,1,2].includes(result.killTicketPenalty))result.killTicketPenalty=1;
  result.renderScale=Math.max(.5,Math.min(1.25,Number(result.renderScale)||1));result.fov=Math.max(65,Math.min(100,Number(result.fov)||79));result.sensitivity=Math.max(.07,Math.min(.65,Number(result.sensitivity)||.22));result.volume=Math.max(0,Math.min(1,Number(result.volume)||0));return result;
 }catch{return {...defaults}}
}
const messages={
 en:{play:'DEPLOY',resume:'RESUME BATTLE',settings:'BATTLE SETUP',battleTab:'BATTLE',controlsTab:'CONTROLS',graphicsTab:'GRAPHICS',audioTab:'AUDIO',language:'LANGUAGE',size:'BATTLE SIZE',difficulty:'AI DIFFICULTY',tickets:'STARTING TICKETS',penalty:'TICKET LOSS / ELIMINATION',graphics:'QUALITY PRESET',sound:'MASTER VOLUME',sensitivity:'MOUSE SENSITIVITY',fov:'FIELD OF VIEW',
  low:'LOW',medium:'MEDIUM',high:'HIGH',easy:'RECRUIT',normal:'REGULAR',hard:'VETERAN',intro:'YOUR WAR. A LIVING FRONTLINE.',desc:'Two autonomous armies. Five contested sectors. One soldier: you.',online:'LOCAL SIMULATION · NO LOGIN · NO MULTIPLAYER',mission:'CONQUEST // OPERATION IRONFRONT',resumeHint:'Click Resume to lock your cursor.',
  pause:'BATTLE PAUSED',restart:'RESTART MATCH',menu:'MAIN MENU',respawn:'KIA · REDEPLOY',base:'MAIN BASE',spawn:'SELECT A DEPLOYMENT LOCATION',victory:'VICTORY',defeat:'DEFEAT',result:'BATTLE COMPLETE',score:'SCOREBOARD',map:'TACTICAL MAP',you:'YOU',team:'FACTION',kills:'KILLS',deaths:'DEATHS',time:'TIME',health:'HEALTH',ammo:'AMMO',reload:'RELOADING',capture:'CAPTURING',contest:'CONTESTED',free:'NEUTRAL',
  guide:'WASD Move  •  Mouse Aim  •  LMB Fire  •  RMB ADS  •  Shift Sprint  •  Ctrl/C Crouch  •  Space Jump  •  R Reload  •  1/2 Weapon  •  G Grenade  •  X Gadget  •  Q Support  •  E Vehicle  •  M Map  •  Tab Scoreboard  •  Esc Pause',experimental:'64v64 is experimental. 32v32 is the primary target.',debug:'F3: developer diagnostics',weapon:'WEAPON',reserve:'RESERVE',vehicle:'ARMORED VEHICLE',armor:'ARMOR',enterVehicle:'E Enter vehicle',exitVehicle:'E Exit vehicle',qualityNote:'High enables denser foliage, 2048px dynamic shadows, atmospheric smoke and higher render resolution. Changes apply when a battle starts.',audioNote:'Combat audio is generated locally with Web Audio; no remote assets are required.'},
 zh:{play:'开始部署',resume:'继续战斗',settings:'战局设置',battleTab:'战局',controlsTab:'操作',graphicsTab:'画面',audioTab:'音频',language:'语言',size:'战场规模',difficulty:'AI 难度',tickets:'初始票数',penalty:'每次阵亡扣除票数',graphics:'画质预设',sound:'主音量',sensitivity:'鼠标灵敏度',fov:'视野 FOV',
  low:'低',medium:'中',high:'高',easy:'新兵',normal:'普通',hard:'老兵',intro:'你的战场，持续变化的前线。',desc:'两支自主作战的军队，五个争夺据点，而你是其中一名士兵。',online:'本地模拟 · 无需登录 · 无需联机',mission:'征服模式 // 铁线行动',resumeHint:'点击继续战斗锁定鼠标。',
  pause:'游戏已暂停',restart:'重新开始',menu:'返回主菜单',respawn:'阵亡 · 重新部署',base:'主基地',spawn:'选择复活位置',victory:'胜利',defeat:'失败',result:'战局结束',score:'计分板',map:'战术地图',you:'你',team:'阵营',kills:'击杀',deaths:'阵亡',time:'时间',health:'生命值',ammo:'弹药',reload:'换弹中',capture:'正在占领',contest:'争夺中',free:'中立',
  guide:'WASD 移动 · 鼠标瞄准 · 左键开火 · 右键瞄准 · Shift 冲刺 · Ctrl/C 下蹲 · 空格跳跃 · R 换弹 · 1/2 切枪 · G 投掷 · X 装备 · Q 支援 · E 载具 · M 地图 · Tab 计分板 · Esc 暂停',experimental:'64v64 为实验模式；32v32 是主要设计目标。',debug:'F3：开发调试数据',weapon:'武器',reserve:'备弹',vehicle:'装甲载具',armor:'装甲值',enterVehicle:'E 进入载具',exitVehicle:'E 离开载具',qualityNote:'高画质会启用更密集的植被、2048px 动态阴影、大气烟雾与更高渲染分辨率；重新部署战局后生效。',audioNote:'战斗音效由 Web Audio 在本地生成，不需要远程音频资源。'}
} as const;

type MenuTab='battle'|'controls'|'graphics'|'audio';
export class UI {
 readonly host:HTMLElement;readonly canvas:HTMLCanvasElement;readonly modal:HTMLElement;readonly hud:HTMLElement;readonly controls:HTMLElement;
 readonly minimap:HTMLCanvasElement;readonly fullmap:HTMLCanvasElement;readonly tactical:HTMLElement;readonly scoreboard:HTMLElement;readonly killfeed:HTMLElement;readonly debug:HTMLElement;
 settings:GameOptions;screen:'menu'|'pause'|'respawn'|'end'|'support'|'none'='menu';
 loadout:Loadout=(()=>{try{return validateLoadout(JSON.parse(localStorage.getItem('ironfront-loadout')||'{}'))}catch{return validateLoadout(null)}})();
 onSupport:(id:SupportId,at:string)=>void=()=>{};
 onStart:(options:GameOptions)=>void=()=>{};onResume:()=>void=()=>{};onRespawn:(at:string)=>void=()=>{};onMenu:()=>void=()=>{};onChange:(opts:GameOptions)=>void=()=>{};
 private supportTarget='C';
 resetBattleState(){this.notices=[];this.lastHud=0;this.supportTarget='C';this.killfeed.innerHTML='';this.hud.classList.remove('scoped','aiming','firing','hurt');this.tactical.classList.add('hidden');this.scoreboard.classList.add('hidden');this.debug.classList.add('hidden')}
 private notices:{value:string;time:number}[]=[];private lastHud=0;private menuTab:MenuTab='battle';
 constructor(host:HTMLElement){this.host=host;this.settings=savedOptions();
  host.innerHTML=`<canvas id="battle-canvas"></canvas><div id="damage-vignette"></div><div id="hud" class="hud hidden"><div class="hud-top"><div class="brand-mini">IRON<span>FRONT</span> <small>CONQUEST</small></div><div id="tickets"></div><div id="timer"></div></div><div id="objectives"></div><div id="major-event" class="major-event hidden"></div><div id="rp-balance"></div><div id="optic-mask" aria-hidden="true"><div class="optic-reticle"><span></span></div></div><div id="crosshair"><span></span><span></span><span></span><span></span></div><div id="hitmarker" class="hidden">✕</div><div class="hud-bottom"><div><div id="player-stats"></div><div id="squad-info"></div></div><div class="map-container"><canvas id="minimap" width="220" height="220"></canvas><label>SECTOR INTEL</label></div></div><div id="sector-status"></div><div id="killfeed"></div><div id="action-help"></div></div><div id="modal"></div><div id="tactical" class="panel-overlay hidden"><div class="tactical-title"></div><canvas id="fullmap" width="550" height="550"></canvas></div><div id="scoreboard" class="panel-overlay hidden"></div><div id="debug" class="debug hidden"></div>`;
  this.canvas=host.querySelector('#battle-canvas')!;this.hud=host.querySelector('#hud')!;this.modal=host.querySelector('#modal')!;this.controls=host.querySelector('#action-help')!;this.minimap=host.querySelector('#minimap')!;this.fullmap=host.querySelector('#fullmap')!;this.tactical=host.querySelector('#tactical')!;this.scoreboard=host.querySelector('#scoreboard')!;this.killfeed=host.querySelector('#killfeed')!;this.debug=host.querySelector('#debug')!;this.menu();
 }
 text(key:keyof typeof messages.en):string{return messages[this.settings.language][key]}
 private eventName(kind:'ARTILLERY'|'COUNTER_OFFENSIVE'|'ARMORED_PUSH'){if(this.settings.language==='zh')return kind==='ARTILLERY'?'炮火压制':kind==='COUNTER_OFFENSIVE'?'反攻浪潮':'装甲突击';return kind==='ARTILLERY'?'ARTILLERY BARRAGE':kind==='COUNTER_OFFENSIVE'?'COUNTER-OFFENSIVE':'ARMORED PUSH'}
 private intentName(intent:string){if(this.settings.language==='zh')return ({ATTACK:'进攻',DEFEND:'防守',FLANK:'侧翼',REINFORCE:'增援'} as Record<string,string>)[intent]??intent;return intent}
 private opt<T extends string|number>(value:T,label:string,selected:T){return `<option value="${value}" ${value===selected?'selected':''}>${label}</option>`}
 private battlePanel(){const t=(k:keyof typeof messages.en)=>this.text(k);return `<div class="settings-title">${t('settings')}</div><div class="form-grid"><label>${t('size')}<select id="setup-size">${this.opt(8,'8 vs 8',this.settings.size)}${this.opt(16,'16 vs 16',this.settings.size)}${this.opt(32,'32 vs 32 · TARGET',this.settings.size)}${this.opt(64,'64 vs 64 · EXP',this.settings.size)}</select></label><label>${t('difficulty')}<select id="setup-difficulty">${this.opt('easy',t('easy'),this.settings.difficulty)}${this.opt('normal',t('normal'),this.settings.difficulty)}${this.opt('hard',t('hard'),this.settings.difficulty)}</select></label><label>${t('tickets')}<select id="setup-tickets">${this.opt(300,'300',this.settings.tickets)}${this.opt(500,'500',this.settings.tickets)}${this.opt(800,'800',this.settings.tickets)}</select></label><label>${t('penalty')}<select id="setup-penalty">${this.opt(0,'0',this.settings.killTicketPenalty)}${this.opt(1,'1',this.settings.killTicketPenalty)}${this.opt(2,'2',this.settings.killTicketPenalty)}</select></label></div><p class="setup-note">${t('experimental')}</p>`}
 private graphicsPanel(){const t=(k:keyof typeof messages.en)=>this.text(k);return `<div class="settings-title">${t('graphicsTab')}</div><div class="form-grid"><label>${t('graphics')}<select id="setup-quality">${this.opt('high',t('high'),this.settings.quality)}${this.opt('medium',t('medium'),this.settings.quality)}${this.opt('low',t('low'),this.settings.quality)}</select></label><label>${t('fov')}<input id="setup-fov" type="range" min="65" max="100" value="${this.settings.fov}"/><output>${this.settings.fov}°</output></label></div><p class="setup-note">${t('qualityNote')}</p>`}
 private audioPanel(){const t=(k:keyof typeof messages.en)=>this.text(k);return `<div class="settings-title">${t('audioTab')}</div><div class="form-grid"><label>${t('sound')}<input id="setup-volume" type="range" min="0" max="100" value="${Math.round(this.settings.volume*100)}"/><output>${Math.round(this.settings.volume*100)}%</output></label></div><p class="setup-note">${t('audioNote')}</p>`}
 private controlsPanel(){const rows=[['W A S D',this.settings.language==='zh'?'移动':'Move'],['MOUSE',this.settings.language==='zh'?'观察 / 瞄准':'Look / Aim'],['LMB / RMB',this.settings.language==='zh'?'开火 / 举枪瞄准':'Fire / ADS'],['SHIFT',this.settings.language==='zh'?'冲刺':'Sprint'],['CTRL / C',this.settings.language==='zh'?'下蹲':'Crouch'],['SPACE',this.settings.language==='zh'?'跳跃':'Jump'],['R',this.settings.language==='zh'?'换弹':'Reload'],['1 / 2',this.settings.language==='zh'?'切换武器':'Switch weapon'],['Q / G / X',this.settings.language==='zh'?'支援 / 投掷 / 装备':'Support / Grenade / Gadget'],['E',this.settings.language==='zh'?'进入 / 离开装甲载具':'Enter / exit armored vehicle'],['M / TAB',this.settings.language==='zh'?'战术地图 / 计分板':'Map / Scoreboard'],['F3',this.settings.language==='zh'?'开发调试':'Diagnostics']];return `<div class="settings-title">${this.text('controlsTab')}</div><div class="control-list">${rows.map(([k,v])=>`<div><kbd>${k}</kbd><span>${v}</span></div>`).join('')}</div><label class="slider-row">${this.text('sensitivity')}<input id="setup-sensitivity" type="range" min="7" max="65" value="${Math.round(this.settings.sensitivity*100)}"/><output>${this.settings.sensitivity.toFixed(2)}</output></label>`}
 private panel(){if(this.menuTab==='controls')return this.controlsPanel();if(this.menuTab==='graphics')return this.graphicsPanel();if(this.menuTab==='audio')return this.audioPanel();return this.battlePanel()}
 private saveSettings(){const q=(s:string)=>this.modal.querySelector<HTMLInputElement|HTMLSelectElement>(s),num=(s:string,fallback:number)=>Number(q(s)?.value??fallback);
  if(q('#setup-size'))this.settings.size=num('#setup-size',this.settings.size) as GameOptions['size'];if(q('#setup-difficulty'))this.settings.difficulty=q('#setup-difficulty')!.value as GameOptions['difficulty'];if(q('#setup-tickets'))this.settings.tickets=num('#setup-tickets',this.settings.tickets);if(q('#setup-penalty'))this.settings.killTicketPenalty=num('#setup-penalty',this.settings.killTicketPenalty);
  if(q('#setup-quality'))this.settings.quality=q('#setup-quality')!.value as GraphicsQuality;if(q('#setup-volume'))this.settings.volume=num('#setup-volume',this.settings.volume*100)/100;if(q('#setup-sensitivity'))this.settings.sensitivity=num('#setup-sensitivity',this.settings.sensitivity*100)/100;if(q('#setup-fov'))this.settings.fov=num('#setup-fov',this.settings.fov);
  this.persist();this.onChange(this.settings);this.modal.querySelectorAll<HTMLInputElement>('input[type="range"]').forEach(input=>{const out=input.parentElement?.querySelector('output');if(out)out.textContent=input.id==='setup-volume'?`${input.value}%`:input.id==='setup-fov'?`${input.value}°`:(Number(input.value)/100).toFixed(2)})
 }
 private persist(){try{localStorage.setItem('ironfront-options',JSON.stringify(this.settings))}catch{/* private mode */}}
 private bindForm(){this.modal.querySelectorAll('select,input').forEach(el=>el.addEventListener('input',()=>this.saveSettings()))}
 private langSwitch(back:'menu'|'pause'){this.settings.language=this.settings.language==='en'?'zh':'en';this.persist();if(back==='menu')this.menu();else this.pause()}
 menu(){this.screen='menu';this.hud.classList.add('hidden');this.tactical.classList.add('hidden');this.scoreboard.classList.add('hidden');this.modal.className='overlay menu';
  const nav=(tab:MenuTab,label:string)=>`<button class="menu-tab ${this.menuTab===tab?'active':''}" data-tab="${tab}">${label}</button>`;
  this.modal.innerHTML=`<div class="menu-accent"></div><div class="menu-showcase" aria-hidden="true"><div class="showcase-scan"></div><div class="showcase-heading">LIVE FRONTLINE <span>◉</span></div><div class="showcase-map"><div class="showcase-line"></div><i>A</i><i>B</i><i>C</i><i>D</i><i>E</i></div><div class="showcase-count">05 <small>CONTROL SECTORS</small></div><p>TWO ARMIES · ONE FRONTLINE</p></div><div class="menu-content"><div class="eyebrow">PROJECT <b>IRONFRONT</b> / 0.6.0</div><h1>IRON<span>FRONT</span></h1><h2>${this.text('intro')}</h2><p class="tagline">${this.text('desc')}</p><p class="local-chip">${this.text('online')}</p><div class="menu-tabs">${nav('battle',this.text('battleTab'))}${nav('controls',this.text('controlsTab'))}${nav('graphics',this.text('graphicsTab'))}${nav('audio',this.text('audioTab'))}</div><div class="setup-card">${this.panel()}<label>Render scale / 分辨率缩放<select id="setup-render-scale">${[.5,.75,1,1.25].map(v=>this.opt(v,`${Math.round(v*100)}%`,this.settings.renderScale)).join('')}</select></label></div>${this.loadoutPanel()}<div class="buttons"><button id="play" class="primary">${this.text('play')} <span>↗</span></button><button id="language" class="secondary">${this.settings.language==='en'?'简体中文':'ENGLISH'}</button></div><p class="menu-footer">${this.text('guide')}</p><small class="muted">${this.text('debug')}</small></div>`;
  this.bindLoadout();this.bindForm();const scale=this.modal.querySelector<HTMLSelectElement>('#setup-render-scale');scale?.addEventListener('change',()=>{this.settings.renderScale=Number(scale.value);this.persist()});this.modal.querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.addEventListener('click',()=>{this.saveSettings();this.menuTab=b.dataset.tab as MenuTab;this.menu()}));this.modal.querySelector('#play')?.addEventListener('click',()=>{this.saveSettings();this.onStart({...this.settings})});this.modal.querySelector('#language')?.addEventListener('click',()=>this.langSwitch('menu'));
 }
 pause(){this.screen='pause';this.modal.className='overlay pause';this.modal.innerHTML=`<div class="pause-card"><div class="eyebrow">IRONFRONT / SYSTEM</div><h2>${this.text('pause')}</h2><p>${this.text('resumeHint')}</p><button class="primary" id="resume">${this.text('resume')}</button><button class="secondary" id="restart">${this.text('restart')}</button><button class="secondary" id="quit">${this.text('menu')}</button><button class="small-button" id="lang">${this.settings.language==='en'?'简体中文':'ENGLISH'}</button><p class="menu-footer">${this.text('guide')}</p></div>`;this.modal.querySelector('#resume')?.addEventListener('click',()=>this.onResume());this.modal.querySelector('#restart')?.addEventListener('click',()=>this.onStart({...this.settings}));this.modal.querySelector('#quit')?.addEventListener('click',()=>this.onMenu());this.modal.querySelector('#lang')?.addEventListener('click',()=>this.langSwitch('pause'))}
 dead(battle:Battle){this.screen='respawn';this.modal.className='overlay respawn';const locations=[{id:'BASE',name:this.text('base')},...battle.points.filter(p=>p.owner==='blue').map(p=>({id:p.id,name:`${p.id} · ${this.settings.language==='zh'?p.zh:p.name}`}))];this.modal.innerHTML=`<div class="pause-card"><div class="eyebrow">REINFORCEMENT REQUIRED</div><h2>${this.text('respawn')}</h2><p>${this.text('spawn')}</p>${this.loadoutPanel()}<div class="spawn-grid">${locations.map((l,i)=>`<button data-spawn="${l.id}" class="${i===0?'primary':'secondary'}">${l.name} ↗</button>`).join('')}</div><small class="muted">K ${battle.player.kills} / D ${battle.player.deaths} · ${this.text('time')}: ${Math.floor(battle.elapsed)}s</small></div>`;this.bindLoadout();this.modal.querySelectorAll<HTMLElement>('[data-spawn]').forEach(b=>b.addEventListener('click',()=>this.onRespawn(b.dataset.spawn??'BASE')))}
 end(battle:Battle){this.screen='end';this.modal.className='overlay end';const won=battle.winner==='blue';this.modal.innerHTML=`<div class="pause-card"><div class="eyebrow">${this.text('result')}</div><h2 class="${won?'win':'lost'}">${this.text(won?'victory':'defeat')}</h2><p>BLUE ${Math.ceil(battle.tickets.blue)} : ${Math.ceil(battle.tickets.red)} RED</p><p>${this.text('kills')}: ${battle.player.kills} · ${this.text('deaths')}: ${battle.player.deaths}</p><button id="again" class="primary">${this.text('restart')}</button><button id="back" class="secondary">${this.text('menu')}</button></div>`;this.modal.querySelector('#again')?.addEventListener('click',()=>this.onStart({...this.settings}));this.modal.querySelector('#back')?.addEventListener('click',()=>this.onMenu())}
 private loadoutPanel(){
  const zh=this.settings.language==='zh',select=(id:string,title:string,ids:string[],current:string)=>`<label>${title}<select id="loadout-${id}">${ids.map(v=>this.opt(v,WEAPONS[v as keyof typeof WEAPONS]?(zh?WEAPONS[v as keyof typeof WEAPONS].zh:WEAPONS[v as keyof typeof WEAPONS].name):({medkit:zh?'医疗包':'Medkit',repair:zh?'维修工具':'Repair tool',frag:zh?'破片手雷':'Frag',smoke:zh?'烟雾弹':'Smoke'} as Record<string,string>)[v]!,current)).join('')}</select></label>`;
  return `<section class="loadout-panel"><h3>${zh?'出生配装':'DEPLOYMENT LOADOUT'}</h3><div class="form-grid">${select('primary',zh?'主武器':'Primary',WEAPON_ORDER.filter(id=>id!=='pistol'),this.loadout.primary)}${select('secondary',zh?'副武器':'Secondary',['pistol','marksman'],this.loadout.secondary)}${select('gadget',zh?'装备 · X 使用':'Equipment · X',['medkit','repair'],this.loadout.gadget)}${select('throwable',zh?'投掷物 · G 投掷':'Throwable · G',['frag','smoke'],this.loadout.throwable)}</div><p id="weapon-spec"></p><small>${zh?'配置自动保存，下次出生生效。':'Saved automatically; applies on deployment.'}</small></section>`;
 }
 private bindLoadout(){
  const update=()=>{const value={...this.loadout};for(const key of ['primary','secondary','gadget','throwable'] as const){const el=this.modal.querySelector<HTMLSelectElement>(`#loadout-${key}`);if(el)Object.assign(value,{[key]:el.value})}this.loadout=validateLoadout(value);const secondary=this.modal.querySelector<HTMLSelectElement>('#loadout-secondary');if(secondary)secondary.value=this.loadout.secondary;try{localStorage.setItem('ironfront-loadout',JSON.stringify(this.loadout))}catch{/* Storage unavailable: keep the session configuration. */}const w=WEAPONS[this.loadout.primary],el=this.modal.querySelector('#weapon-spec');if(el)el.textContent=`${w.damage} DMG · ${Math.round(60/w.fireInterval)} RPM · ${w.magazine} MAG · ${w.effectiveRange}m · ${w.reload}s reload`;};
  this.modal.querySelectorAll('[id^="loadout-"]').forEach(el=>el.addEventListener('change',update));update();
 }
 support(battle:Battle,message=''){
  this.screen='support';this.modal.className='overlay support-overlay';const zh=this.settings.language==='zh';
  this.modal.innerHTML=`<div class="support-card"><h2>${zh?'战场征用':'BATTLEFIELD REQUISITION'}</h2><p>${battle.requisitionPoints} RP · ${zh?'击杀、助攻、防守、占点、摧毁载具获取积分':'Earn RP through combat and objectives'}</p><label>${zh?'支援目标据点（载具停放主基地）':'Target sector (vehicles arrive at main base)'}<select id="support-target">${battle.points.map(p=>`<option value="${p.id}" ${p.id===this.supportTarget?'selected':''}>${p.id} · ${zh?p.zh:p.name}</option>`).join('')}</select></label><div class="support-grid">${(Object.keys(SUPPORTS) as SupportId[]).map(id=>{const d=SUPPORTS[id],cool=Math.ceil(Math.max(0,(battle.supportCooldowns[id]??0)-battle.elapsed));return `<button data-support="${id}" ${cool||battle.requisitionPoints<d.cost?'disabled':''}><b>${zh?d.zh:d.name}</b><span>${d.cost} RP${cool?` · ${cool}s`:''}</span><small>${zh?({recon:'目标周围 105m 近似情报，持续 12 秒',smoke:'区域烟幕持续 22 秒，阻断实际视线',artillery:'5 秒预警后四次真实打击',reinforce:'加快己方 AI 复活并提升士气',scout:'基地部署快速轻型车',ifv:'基地部署自动炮步战车',tank:'基地部署重装甲和高伤害主炮'} as Record<SupportId,string>)[id]:d.description}</small></button>`}).join('')}</div><p role="status">${message}</p><button id="support-close" class="primary">${zh?'返回战场 · Q / Esc':'Return to battle · Q / Esc'}</button></div>`;
  this.modal.querySelector<HTMLSelectElement>('#support-target')?.addEventListener('change',e=>{this.supportTarget=(e.target as HTMLSelectElement).value});
  this.modal.querySelector('#support-close')?.addEventListener('click',()=>this.onResume());
  this.modal.querySelectorAll<HTMLElement>('[data-support]').forEach(el=>el.addEventListener('click',()=>this.onSupport(el.dataset.support as SupportId,this.modal.querySelector<HTMLSelectElement>('#support-target')!.value)));
 }
 hideOverlay(){this.screen='none';this.modal.className='hidden';this.modal.innerHTML='';this.hud.classList.remove('hidden');this.controls.textContent=this.text('guide')}
 showHit(){const el=this.hud.querySelector('#hitmarker')!;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),110)}
 logEvents(events:BattleEvent[],battle:Battle){for(const e of events){if(e.type==='death'){const killer=e.killer===null?(this.settings.language==='zh'?'战场火力':'BATTLEFIELD STRIKE'):e.killer===0?this.text('you'):`${battle.soldiers[e.killer]?.team==='blue'?'BLU':'RED'}-${e.killer.toString().padStart(2,'0')}`,victim=e.victim===0?this.text('you'):`${e.team==='blue'?'BLU':'RED'}-${e.victim.toString().padStart(2,'0')}`;this.notices.unshift({value:`${killer} <span class="kill-icon">✚</span> ${victim}`,time:battle.elapsed+5})}else if(e.type==='rp'&&e.amount>=25)this.notices.unshift({value:`+${e.amount} RP · ${e.reason}`,time:battle.elapsed+4});else if(e.type==='support')this.notices.unshift({value:`${this.settings.language==='zh'?SUPPORTS[e.kind].zh:SUPPORTS[e.kind].name} · ACTIVE`,time:battle.elapsed+5});else if(e.type==='capture'&&e.owner)this.notices.unshift({value:`${e.id} SECURED BY ${e.owner.toUpperCase()}`,time:battle.elapsed+6});else if(e.type==='majorEvent'&&e.action!=='end'){const verb=e.action==='warning'?(this.settings.language==='zh'?'预警':'WARNING'):(this.settings.language==='zh'?'已开始':'ACTIVE');this.notices.unshift({value:`⚠ ${this.eventName(e.kind)} · ${e.objective} · ${verb}`,time:battle.elapsed+8})}}this.notices=this.notices.slice(0,8).filter(n=>n.time>battle.elapsed)}
 drawHUD(battle:Battle,seconds:number){if(this.screen==='respawn')this.modal.querySelectorAll<HTMLButtonElement>('[data-spawn]').forEach(b=>{b.disabled=battle.elapsed<battle.player.respawnAt});if(seconds-this.lastHud<.11)return;this.lastHud=seconds;const blue=Math.ceil(battle.tickets.blue),red=Math.ceil(battle.tickets.red);this.hud.querySelector('#tickets')!.innerHTML=`<span class="blue-ticket">◈ BLUE ${blue}</span><b>VS</b><span class="red-ticket">${red} RED ◈</span>`;const minutes=Math.floor(battle.elapsed/60).toString().padStart(2,'0'),secs=Math.floor(battle.elapsed%60).toString().padStart(2,'0');this.hud.querySelector('#timer')!.textContent=`${minutes}:${secs}`;this.hud.querySelector('#objectives')!.innerHTML=battle.points.map(p=>`<div class="objective ${p.owner??'neutral'}" title="${this.settings.language==='zh'?p.zh:p.name}"><strong>${p.id}</strong><div class="control"><span style="width:${Math.abs(p.control)}%;background:${p.control>0?'#65bffe':'#ff8472'}"></span></div></div>`).join('');
  this.hud.querySelector('#rp-balance')!.textContent=`${battle.requisitionPoints} RP · Q ${this.settings.language==='zh'?'支援':'SUPPORT'} · G ${battle.grenadeCount} · X ${battle.gadgetCharges}${battle.supports.length?' · '+battle.supports.map(s=>`${s.kind} ${Math.ceil(s.ends-battle.elapsed)}s`).join(' / '):''}`;
  const def=battle.activeWeapon,weaponName=this.settings.language==='zh'?def.zh:def.name,vehicle=battle.playerVehicle;if(vehicle)this.hud.querySelector('#player-stats')!.innerHTML=`<div class="stat-head">${this.text('vehicle')} / ${this.text('armor')}</div><strong>${Math.ceil(vehicle.hp)} <em>ARMOR</em></strong><div class="healthbar"><span style="width:${vehicle.hp/vehicle.maxHp*100}%"></span></div><strong class="ammo">∞<small> / CANNON</small></strong><div class="reload">${vehicle.team.toUpperCase()} · ${VEHICLE_TYPES[vehicle.kind].name}</div>`;else this.hud.querySelector('#player-stats')!.innerHTML=`<div class="stat-head">${this.text('health')} / ${this.text('ammo')}</div><strong>${Math.ceil(battle.player.hp)} <em>HP</em></strong><div class="healthbar"><span style="width:${battle.player.hp}%"></span></div><strong class="ammo">${battle.playerAmmo}<small> / ${battle.playerReserveAmmo}</small></strong><div class="reload">${battle.isReloading()?this.text('reload'):`${weaponName} · ${def.automatic?'AUTO':'SEMI'}`}</div>`;
  const order=battle.getSquadTargets().find(o=>o.team==='blue'&&o.squad===battle.player.squad),alive=battle.soldiers.filter(s=>s.team==='blue'&&s.squad===battle.player.squad&&s.alive).length;this.hud.querySelector('#squad-info')!.textContent=`SQUAD ${battle.player.squad+1} · ${alive}/4 · ${order?this.intentName(order.intent):'ORDER'} ${order?.objective??'—'}`;
  const major=battle.getMajorEvent(),majorEl=this.hud.querySelector<HTMLElement>('#major-event')!;if(major){const remaining=Math.max(0,Math.ceil(major.endsAt-battle.elapsed)),warning=major.kind==='ARTILLERY'&&battle.elapsed<major.warningUntil;majorEl.className=`major-event ${major.team}${warning?' warning':''}`;majorEl.textContent=`${warning?'⚠ ':''}${this.eventName(major.kind)} · ${major.objective} · ${remaining}s`}else{majorEl.className='major-event hidden'};
  const nearbyVehicle=!vehicle?battle.vehicles.find(v=>v.alive&&v.team==='blue'&&dist(v.pos,battle.player.pos)<7.2):null;this.controls.textContent=vehicle?this.text('exitVehicle'):nearbyVehicle?this.text('enterVehicle'):this.text('guide');
  const nearest=battle.points.filter(p=>dist(p,battle.player.pos)<25).sort((a,b)=>dist(a,battle.player.pos)-dist(b,battle.player.pos))[0];this.hud.querySelector('#sector-status')!.textContent=nearest?`${nearest.id} / ${nearest.contested?this.text('contest'):nearest.owner==='blue'?'SECURED':this.text('capture')}`:'';this.notices=this.notices.filter(n=>n.time>battle.elapsed);this.killfeed.innerHTML=this.notices.map(n=>`<div>${n.value}</div>`).join('');this.renderMap(this.minimap,battle,false)}
 private renderMap(canvas:HTMLCanvasElement,battle:Battle,large:boolean){
  const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width;ctx.clearRect(0,0,w,w);ctx.fillStyle='rgba(7,23,33,.94)';ctx.fillRect(0,0,w,w);
  const project=(p:{x:number;z:number})=>({x:((p.x+MAP_SIZE/2)/MAP_SIZE)*w,y:((p.z+MAP_SIZE/2)/MAP_SIZE)*w});ctx.lineWidth=large?1.5:1;ctx.strokeStyle='#395467';for(let i=1;i<8;i++){const v=i*w/8;ctx.beginPath();ctx.moveTo(v,0);ctx.lineTo(v,w);ctx.moveTo(0,v);ctx.lineTo(w,v);ctx.stroke()}
  ctx.strokeStyle='#596151';ctx.lineWidth=large?13:5;ctx.beginPath();for(const [i,p]of [{x:-311,z:-302},{x:-185,z:-210},{x:-20,z:-93},{x:17,z:81},{x:199,z:157},{x:311,z:302}].entries()){const q=project(p);if(i===0)ctx.moveTo(q.x,q.y);else ctx.lineTo(q.x,q.y)}ctx.stroke();
  for(const [team,p]of Object.entries(BASES) as [Team,{x:number;z:number}][]){const q=project(p);ctx.fillStyle=team==='blue'?'#64baff':'#ff7770';ctx.fillRect(q.x-4,q.y-4,8,8)}
  for(const p of battle.points){const q=project(p);ctx.beginPath();ctx.arc(q.x,q.y,large?14:7,0,7);ctx.fillStyle=p.owner==='blue'?'#2679ae':p.owner==='red'?'#b34646':'#68787c';ctx.fill();ctx.strokeStyle=p.contested?'#fff':'#b0cad3';ctx.lineWidth=p.contested?3:1;ctx.stroke();ctx.fillStyle='white';ctx.font=`bold ${large?15:10}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.id,q.x,q.y)}
  if(large){for(const order of battle.getSquadTargets().filter(o=>o.team==='blue')){const leader=battle.soldiers[order.leaderId];if(!leader?.alive)continue;const a=project(leader.pos),b=project(order.approach);ctx.strokeStyle=order.intent==='FLANK'?'rgba(250,190,130,.55)':'rgba(110,204,246,.36)';ctx.lineWidth=1.2;ctx.setLineDash(order.intent==='FLANK'?[5,4]:[2,4]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=order.intent==='FLANK'?'#f2b983':'#7ed0ef';ctx.fillRect(b.x-2,b.y-2,4,4)}}
  const major=battle.getMajorEvent();if(major){const point=battle.points.find(p=>p.id===major.objective);if(point){const q=project(point),radius=large?27:11;ctx.strokeStyle=major.team==='blue'?'#70d9ff':'#ff9b84';ctx.lineWidth=large?4:2;ctx.setLineDash([7,5]);ctx.beginPath();ctx.arc(q.x,q.y,radius,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}}
  for(const s of battle.soldiers){if(!s.alive||s.player)continue;if(s.team==='red'&&!battle.hasReconContact(s.pos)&&!battle.soldiers.some(a=>a.alive&&a.team==='blue'&&dist(a.pos,s.pos)<115&&!battle.sightBlocked(a.pos,s.pos)))continue;const approximate=s.team==='red'?{x:Math.round(s.pos.x/24)*24,z:Math.round(s.pos.z/24)*24}:s.pos,q=project(approximate);ctx.fillStyle=s.team==='blue'?'#7ecefa':'#fd8b7c';ctx.beginPath();ctx.arc(q.x,q.y,large?3.2:1.7,0,7);ctx.fill()}
  for(const v of battle.vehicles){if(!v.alive)continue;if(v.team==='red'&&!battle.hasReconContact(v.pos)&&!battle.soldiers.some(a=>a.alive&&a.team==='blue'&&dist(a.pos,v.pos)<150&&!battle.sightBlocked(a.pos,v.pos)))continue;const qv=project(v.team==='red'?{x:Math.round(v.pos.x/30)*30,z:Math.round(v.pos.z/30)*30}:v.pos);ctx.fillStyle=v.team==='blue'?'#a8e4ff':'#ffad9f';const r=large?5:3;ctx.fillRect(qv.x-r,qv.y-r,r*2,r*2)}
  const q=project(battle.player.pos);ctx.fillStyle='#fff';ctx.save();ctx.translate(q.x,q.y);ctx.rotate(Math.PI-battle.player.yaw);ctx.beginPath();ctx.moveTo(0,-(large?9:6));ctx.lineTo(-(large?6:4),large?7:5);ctx.lineTo(large?6:4,large?7:5);ctx.closePath();ctx.fill();ctx.restore()
 }
 toggleMap(show:boolean,battle:Battle){this.tactical.classList.toggle('hidden',!show);if(show){this.tactical.querySelector('.tactical-title')!.textContent=this.text('map');this.renderMap(this.fullmap,battle,true)}}
 toggleScore(show:boolean,battle:Battle){this.scoreboard.classList.toggle('hidden',!show);if(!show)return;const rows=[...battle.soldiers].sort((a,b)=>b.kills-a.kills);this.scoreboard.innerHTML=`<div class="score-title">${this.text('score')}</div><table><thead><tr><th>${this.text('team')}</th><th>CALLSIGN</th><th>${this.text('kills')}</th><th>${this.text('deaths')}</th><th>STATE</th></tr></thead><tbody>${rows.map(s=>`<tr class="${s.player?'mine':''}"><td class="${s.team}">${s.team.toUpperCase()}</td><td>${s.player?this.text('you'):`BOT-${s.id.toString().padStart(2,'0')}`}</td><td>${s.kills}</td><td>${s.deaths}</td><td>${s.state}</td></tr>`).join('')}</tbody></table>`}
 setDebug(visible:boolean,battle:Battle,fps:number,draws:number){this.debug.classList.toggle('hidden',!visible);if(!visible)return;const counts:Record<string,number>={};for(const s of battle.soldiers)counts[s.state]=(counts[s.state]??0)+1;const major=battle.getMajorEvent();this.debug.innerHTML=`FPS ${fps.toFixed(0)} | ${draws} draw calls<br>AI ${battle.soldiers.length-1} / ${battle.soldiers.filter(s=>s.alive&&!s.player).length} live · nav failures ${battle.getNavigationFailures()}<br>${Object.entries(counts).map(([s,n])=>`${s}: ${n}`).join(' · ')}<br>Orders: ${battle.getSquadTargets().slice(0,12).map(g=>`${g.team[0]}${g.squad}:${g.intent[0]}-${g.objective}[L${g.leaderId}]`).join(' ')}<br>Major: ${major?`${major.kind} ${major.team} → ${major.objective}`:'none'}<br>Vehicles ${battle.vehicles.map(v=>`${v.team[0]}:${v.alive?Math.ceil(v.hp)+'HP':'DOWN'}:${v.driver}`).join(' · ')}<br>Objectives ${battle.points.map(p=>`${p.id}:${p.owner?.[0]??'-'}${p.contested?'!':''}`).join(' ')}<br>Tickets ${Math.ceil(battle.tickets.blue)} / ${Math.ceil(battle.tickets.red)}`}
}
