// Render actual map geometry; thumbnails never substitute illustrative artwork.
const {chromium}=require('@playwright/test'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.IRONFRONT_CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1280,height:720}});const metrics=[];try{
 for(const mapId of ['industrial-frontier','dust-horizon']){
 await page.goto('http://127.0.0.1:4174');await page.evaluate(id=>localStorage.setItem('ironfront-options',JSON.stringify({mapId:id,size:32,quality:'medium'})),mapId);await page.reload();await page.locator('#play').click();await page.locator('#preparation-operator').waitFor();
 const image=await page.evaluate(()=>{const q=window.__IRONFRONT_QA,w=q.world,b=q.battle;w.render(q.battle,0,{yaw:0,pitch:0,height:1.78,ads:false,moving:false,sprint:false,reload:false,speed:0,side:0,infantryFirstPerson:false});w.weapon.group.visible=false;w.camera.position.set(-90,90,-155);w.camera.lookAt(b.map.definition.id==='dust-horizon'?0:-20,0,b.map.definition.id==='dust-horizon'?30:-93);w.renderer.render(w.scene,w.camera);return w.renderer.domElement.toDataURL('image/png');});fs.mkdirSync('public/maps',{recursive:true});fs.writeFileSync('public/maps/'+mapId+'.png',Buffer.from(image.split(',')[1],'base64'));
 await page.locator('#ready').click();await page.locator('#modal.hidden').waitFor({state:'attached'});const result=await page.evaluate(async()=>{const q=window.__IRONFRONT_QA;const samples=[];let previous=performance.now();for(let i=0;i<100;i++){await new Promise(requestAnimationFrame);const now=performance.now();if(i>=20)samples.push(now-previous);previous=now;}samples.sort((a,b)=>a-b);return {mapId:q.battle.settings.mapId,renderer:'Chrome SwiftShader software WebGL',viewport:[innerWidth,innerHeight],quality:'medium',medianFrameMs:samples[Math.floor(samples.length/2)],p95FrameMs:samples[Math.floor(samples.length*.95)],drawCalls:q.world.renderer.info.render.calls,triangles:q.world.renderer.info.render.triangles,geometries:q.world.renderer.info.memory.geometries,textures:q.world.renderer.info.memory.textures};});metrics.push(result);
 }fs.mkdirSync('docs/qa',{recursive:true});fs.writeFileSync('docs/qa/rendering-019.json',JSON.stringify(metrics,null,2)+'\n');console.log(metrics);
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
