import * as THREE from 'three';
import type {Battle} from '../core/Battle';
import {heightAt} from '../core/math';
import {vehicleMuzzle} from '../vehicles/Vehicle';
/** Visible authority-backed thrown objects, supply crates, parachutes and countermeasures. */
export class FieldVisuals {
 private models=new Map<string,THREE.Group>();
 private actual=document.createElement('div');private impact=document.createElement('div');private status=document.createElement('div');
 constructor(private scene:THREE.Scene){this.actual.className='vehicle-reticle hidden';this.impact.className='vehicle-reticle vehicle-impact hidden';this.status.className='vehicle-lock hidden';document.body.append(this.actual,this.impact,this.status);}
 private remove(key:string){const g=this.models.get(key);if(!g)return;g.removeFromParent();g.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});this.models.delete(key);}
 update(b:Battle,dt:number,camera:THREE.Camera){const active=new Set<string>();
  const ensure=(key:string,create:()=>THREE.Group)=>{active.add(key);let g=this.models.get(key);if(!g){g=create();g.name=key;this.models.set(key,g);this.scene.add(g);}return g;};
  const box=(w:number,h:number,d:number,color:number,x=0,y=0,z=0)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.85}));m.position.set(x,y,z);return m;};
  for(const item of b.grenades){const g=ensure('thrown-'+item.id,()=>{const group=new THREE.Group();const smoke=item.kind==='smoke';group.add(new THREE.Mesh(new THREE.CylinderGeometry(smoke?.1:.13,.13,smoke?.35:.24,8),new THREE.MeshStandardMaterial({color:smoke?0xd2d4c2:0x547245})),box(.13,.05,.13,0x292f2c,0,.19));group.add(box(.04,.15,.05,0x858780,.12,.1));return group;});g.position.set(item.pos.x,item.pos.y,item.pos.z);g.rotation.x+=dt*8;g.rotation.z+=dt*4;}
  for(const item of b.ammoBoxes){const g=ensure('ammo-'+item.id,()=>{const group=new THREE.Group();group.add(box(.8,.48,.52,0x526348,0,.25),box(.86,.08,.58,0x293b32,0,.53));for(const x of [-.25,.25])group.add(box(.055,.5,.55,0xa69e73,x,.28));group.add(box(.3,.03,.02,0xebd287,0,.52,.31));return group;});g.position.set(item.at.x,heightAt(item.at.x,item.at.z),item.at.z);}
  for(const s of b.soldiers)if(s.alive&&s.parachuting){const g=ensure('parachute-'+s.id,()=>{const group=new THREE.Group();const canopy=new THREE.Mesh(new THREE.SphereGeometry(3,12,6,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:s.team==='blue'?0x8cadbf:0xb79a86,side:THREE.DoubleSide}));canopy.scale.y=.35;canopy.position.y=4;group.add(canopy);for(const x of [-1,1])for(const z of [-1,1]){const cord=box(.025,3.7,.025,0xcac5b1,x*.8,2,z*.8);group.add(cord);}return group;});g.position.set(s.pos.x,heightAt(s.pos.x,s.pos.z)+s.altitude,s.pos.z);}
  for(const v of b.vehicles)if(v.alive&&v.flareUntil>b.elapsed&&['jet','helicopter'].includes(v.kind)){for(let i=0;i<8;i++){const g=ensure('flare-'+v.id+'-'+i,()=>{const group=new THREE.Group();group.add(new THREE.Mesh(new THREE.SphereGeometry(.12,6,4),new THREE.MeshBasicMaterial({color:0xffd792})));return group;});const age=5-(v.flareUntil-b.elapsed);g.position.set(v.pos.x+Math.cos(i)*age*5,heightAt(v.pos.x,v.pos.z)+v.altitude+1-age*2,v.pos.z+Math.sin(i)*age*5);}}
  for(const key of this.models.keys())if(!active.has(key))this.remove(key);
  const v=b.playerVehicle;this.actual.classList.toggle('hidden',!v||v.kind==='motorcycle');this.impact.classList.toggle('hidden',!v||v.kind==='motorcycle');this.status.classList.toggle('hidden',!v);
  if(v&&v.kind==='motorcycle'){this.status.textContent='M2 COURIER · 双座无武装 · WASD 驾驶 · 空格刹车 · E 下车';return;}
  if(v){const mg=b.playerSeat===1||v.kind==='scout'||v.weaponSlot===1&&!['aa','jet','helicopter'].includes(v.kind),coax=mg&&b.playerSeat===0&&['tank','ifv'].includes(v.kind),m=vehicleMuzzle(v,mg,coax),yaw=mg&&!coax?v.mgYaw:v.turretYaw,pitch=v.turretPitch;const barrel={x:m.x+Math.sin(yaw)*Math.cos(pitch)*100,y:heightAt(v.pos.x,v.pos.z)+m.y+Math.sin(pitch)*100,z:m.z+Math.cos(yaw)*Math.cos(pitch)*100};const project=(el:HTMLElement,point:{x:number;y:number;z:number})=>{const p=new THREE.Vector3(point.x,point.y,point.z).project(camera);el.classList.toggle('hidden',p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1);el.style.left=(p.x*.5+.5)*innerWidth+'px';el.style.top=(-p.y*.5+.5)*innerHeight+'px';};project(this.actual,barrel);const landing=b.vehicleImpact();if(landing)project(this.impact,landing);this.actual.title='实际炮口方向';this.impact.title='预计落点';this.status.dataset.kind=v.kind;this.status.classList.toggle('incoming',v.incomingUntil>b.elapsed);this.status.textContent=(v.incomingUntil>b.elapsed?'⚠ 导弹来袭 · X 热诱弹  ':v.warningUntil>b.elapsed?'⚠ 正在被锁定 · X 解除锁定  ':'')+`${v.kind==='jet'?`JET · 空速 ${Math.round(v.speed*3.6)} km/h · 高度 ${Math.round(v.altitude)}m · 坡度 ${Math.round(v.roll*180/Math.PI)}° · `:v.kind==='helicopter'?`HELI · ${Math.round(v.speed*3.6)} km/h · 高度 ${Math.round(v.altitude)}m · 升降 ${Math.round(v.verticalVelocity)}m/s · `:v.kind==='motorcycle'?'MOTO · 双座无武装 · ':''}1 主武器 ${['scout','transport'].includes(v.kind)?'机枪':v.ammoMode==='he'?'高爆':'穿甲'} ${['scout','transport'].includes(v.kind)?'':`/ 2 ${['jet','helicopter','aa'].includes(v.kind)?'制导导弹':'同轴机枪'}`} · 当前 ${v.weaponSlot+1} ${['jet','helicopter','aa'].includes(v.kind)&&v.weaponSlot===1?'· '+(v.lockTarget===null?'无法锁定':v.lockProgress<1?'锁定 '+Math.round(v.lockProgress*100)+'%':'已锁定'):''} · X ${v.kind==='scout'?'侦察扫描':v.kind==='transport'?'弹药补给':['jet','helicopter'].includes(v.kind)?'热诱弹':'防护烟幕'} ${v.nextFlare>b.elapsed?'干扰 '+Math.ceil(v.nextFlare-b.elapsed)+'s':'干扰就绪'} · 空心圈 炮口 / 虚线圈 落点`;}
 }
 dispose(){for(const key of this.models.keys())this.remove(key);this.actual.remove();this.impact.remove();this.status.remove();}
}
